/**
 * Kaşık — Ek Tarif Veritabanı
 * 75+ ek tarif: 6+ ay, 8+ ay, 12+ ay kategorilerinde
 * Web kaynaklarından derlenen Türk bebek ek gıda tarifleri
 */

import { RecipeData } from './recipes';

const hoursAgo = (h: number) => new Date(Date.now() - h * 60 * 60 * 1000);

// =============================================
// 6+ AY EK TARİFLER
// =============================================

export const EXTRA_RECIPES_6M: RecipeData[] = [
  {
    id: '30',
    title: 'Havuç Püresi',
    description: 'İlk ek gıdalar için ideal, tatlı ve besleyici havuç püresi.',
    emoji: '🥕',
    ageGroup: '6m',
    prepTime: 15,
    calories: 45,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.9, count: 45 },
    likes: 210, views: 1200, comments: 22,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['İlk Ek Gıda', 'Kolay', 'Sebze'],
    ingredients: [
      { name: 'Havuç', amount: 1, unit: 'orta boy', emoji: '🥕' },
      { name: 'Su', amount: 100, unit: 'ml', emoji: '💧' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Havucu soyup küçük parçalara doğrayın.',
      'Buharda veya suda 12-15 dakika yumuşayana kadar pişirin.',
      'Çatalla veya blenderla pürüzsüz kıvama getirin.',
      'Zeytinyağı ekleyip karıştırın.',
      'Ilık olarak servis edin.',
    ],
    nutrients: [
      { name: 'A Vitamini', value: 835, unit: 'mcg' },
      { name: 'Lif', value: 2.8, unit: 'g' },
      { name: 'Karbonhidrat', value: 10, unit: 'g' },
    ],
    tip: 'Havuç A vitamini deposudur. Buharda pişirmek besin değerini korur.',
    createdAt: hoursAgo(60),
  },
  {
    id: '31',
    title: 'Kabak Püresi',
    description: 'Hafif ve sindirilmesi kolay, bebeğin ilk sebzelerinden.',
    emoji: '🎃',
    ageGroup: '6m',
    prepTime: 12,
    calories: 35,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.7, count: 38 },
    likes: 180, views: 950, comments: 15,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['İlk Ek Gıda', 'Kolay', 'Sebze'],
    ingredients: [
      { name: 'Kabak', amount: 0.5, unit: 'orta boy', emoji: '🎃' },
      { name: 'Su', amount: 50, unit: 'ml', emoji: '💧' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Kabağı soyup çekirdeklerini çıkarın.',
      'Küçük küpler halinde doğrayın.',
      'Buharda 10 dakika pişirin.',
      'Çatalla ezin veya blenderdan geçirin.',
      'Zeytinyağı ekleyip ılık servis edin.',
    ],
    nutrients: [
      { name: 'Karbonhidrat', value: 7, unit: 'g' },
      { name: 'Lif', value: 1.5, unit: 'g' },
      { name: 'C Vitamini', value: 12, unit: 'mg' },
    ],
    tip: 'Kabak sindirilmesi en kolay sebzelerdendir, gaz yapmaz.',
    createdAt: hoursAgo(62),
  },
  {
    id: '32',
    title: 'Armut Püresi',
    description: 'Doğal tatlılığıyla bebeğin severek yiyeceği ilk meyve püresi.',
    emoji: '🍐',
    ageGroup: '6m',
    prepTime: 10,
    calories: 55,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.8, count: 40 },
    likes: 195, views: 1100, comments: 20,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Meyve', 'Kolay', 'İlk Ek Gıda'],
    ingredients: [
      { name: 'Armut', amount: 1, unit: 'küçük', emoji: '🍐' },
      { name: 'Su', amount: 50, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Armutu soyup çekirdeklerini çıkarın.',
      'Küçük parçalara doğrayın.',
      'Buharda 8-10 dakika pişirin veya rendeleyerek çiğ verin.',
      'Çatalla ezin.',
      'Ilık olarak bebeğinize ikram edin.',
    ],
    nutrients: [
      { name: 'Lif', value: 3.1, unit: 'g' },
      { name: 'Karbonhidrat', value: 13, unit: 'g' },
      { name: 'C Vitamini', value: 4, unit: 'mg' },
    ],
    tip: 'Armut en az alerji yapan meyvelerdendir, ilk denemeler için idealdir.',
    createdAt: hoursAgo(63),
  },
  {
    id: '33',
    title: 'Muz Ezmesi',
    description: 'Pişirme gerektirmeyen, pratik ve enerji dolu meyve ezmesi.',
    emoji: '🍌',
    ageGroup: '6m',
    prepTime: 3,
    calories: 85,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.6, count: 55 },
    likes: 230, views: 1500, comments: 25,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Meyve', 'Kolay', 'Pişirmesiz'],
    ingredients: [
      { name: 'Muz', amount: 0.5, unit: 'adet', emoji: '🍌' },
    ],
    steps: [
      'Muzu soyun.',
      'Çatalla iyice ezin.',
      'Pürüzsüz kıvama gelene kadar ezmeye devam edin.',
      'Doğrudan bebeğinize ikram edin.',
    ],
    nutrients: [
      { name: 'Potasyum', value: 200, unit: 'mg' },
      { name: 'Karbonhidrat', value: 20, unit: 'g' },
      { name: 'B6 Vitamini', value: 0.2, unit: 'mg' },
    ],
    tip: 'Kabızlık yapabilir, haftada 2-3 kez verilmesi yeterlidir.',
    createdAt: hoursAgo(64),
  },
  {
    id: '34',
    title: 'Patates Püresi',
    description: 'Doyurucu ve yumuşak, bebeğin ilk katı gıdalarından.',
    emoji: '🥔',
    ageGroup: '6m',
    prepTime: 20,
    calories: 80,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.5, count: 42 },
    likes: 175, views: 1050, comments: 18,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Sebze', 'Kolay', 'Doyurucu'],
    ingredients: [
      { name: 'Patates', amount: 1, unit: 'küçük', emoji: '🥔' },
      { name: 'Su', amount: 150, unit: 'ml', emoji: '💧' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Patatesi soyup küçük küpler halinde doğrayın.',
      'Tencereye koyup suyunu ekleyin.',
      'Kısık ateşte 15-20 dakika yumuşayana kadar pişirin.',
      'Suyu süzüp çatalla iyice ezin.',
      'Zeytinyağı ekleyip karıştırın.',
    ],
    nutrients: [
      { name: 'Karbonhidrat', value: 17, unit: 'g' },
      { name: 'Potasyum', value: 320, unit: 'mg' },
      { name: 'C Vitamini', value: 10, unit: 'mg' },
    ],
    tip: 'Haşlama suyu yerine anne sütü ekleyerek daha besleyici hale getirebilirsiniz.',
    createdAt: hoursAgo(65),
  },
  {
    id: '35',
    title: 'Havuç-Elma Püresi',
    description: 'Sebze ve meyvenin mükemmel uyumu, tatlı-tuzlu denge.',
    emoji: '🥕',
    ageGroup: '6m',
    prepTime: 18,
    calories: 65,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.7, count: 35 },
    likes: 155, views: 880, comments: 14,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Sebze', 'Meyve', 'Kolay'],
    ingredients: [
      { name: 'Havuç', amount: 1, unit: 'küçük', emoji: '🥕' },
      { name: 'Elma', amount: 0.5, unit: 'adet', emoji: '🍎' },
      { name: 'Su', amount: 100, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Havucu soyup ince dilimleyin.',
      'Elmayı soyup çekirdeklerini çıkarıp doğrayın.',
      'Her ikisini buharda 15 dakika pişirin.',
      'Blenderla pürüzsüz kıvama getirin.',
      'Ilık olarak servis edin.',
    ],
    nutrients: [
      { name: 'A Vitamini', value: 500, unit: 'mcg' },
      { name: 'C Vitamini', value: 8, unit: 'mg' },
      { name: 'Lif', value: 2.5, unit: 'g' },
    ],
    tip: 'Havuç ve elma birbirini tamamlayan harika bir ikili. Bebeğin sebzeye alışmasına yardımcı olur.',
    createdAt: hoursAgo(66),
  },
  {
    id: '36',
    title: 'Yoğurtlu Kabak',
    description: 'Probiyotik yoğurt ile sindirim dostu kabak birleşimi.',
    emoji: '🥒',
    ageGroup: '6m',
    prepTime: 15,
    calories: 55,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.6, count: 30 },
    likes: 140, views: 780, comments: 12,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['milk'],
    tags: ['Sebze', 'Yoğurtlu', 'Probiyotik'],
    ingredients: [
      { name: 'Kabak', amount: 0.5, unit: 'orta boy', emoji: '🎃' },
      { name: 'Yoğurt', amount: 2, unit: 'yemek kaşığı', emoji: '🥛', isAllergen: true },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Kabağı soyup küçük parçalara doğrayın.',
      'Buharda 10 dakika pişirin.',
      'Çatalla ezin ve soğumaya bırakın.',
      'Ilıyınca yoğurt ve zeytinyağı ekleyip karıştırın.',
    ],
    nutrients: [
      { name: 'Protein', value: 2, unit: 'g' },
      { name: 'Kalsiyum', value: 45, unit: 'mg' },
      { name: 'Karbonhidrat', value: 8, unit: 'g' },
    ],
    tip: 'Yoğurdu ısıya maruz bırakmayın, soğuduktan sonra ekleyin ki probiyotikler canlı kalsın.',
    createdAt: hoursAgo(67),
  },
  {
    id: '37',
    title: 'Brokoli Püresi',
    description: 'Demir ve C vitamini zengini süper besin püresi.',
    emoji: '🥦',
    ageGroup: '6m',
    prepTime: 12,
    calories: 30,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.4, count: 28 },
    likes: 120, views: 700, comments: 10,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Sebze', 'Demir', 'Kolay'],
    ingredients: [
      { name: 'Brokoli', amount: 3, unit: 'çiçek', emoji: '🥦' },
      { name: 'Su', amount: 50, unit: 'ml', emoji: '💧' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Brokoli çiçeklerini yıkayın.',
      'Buharda 8-10 dakika pişirin.',
      'Blenderla pürüzsüz kıvama getirin.',
      'Zeytinyağı ekleyip ılık servis edin.',
    ],
    nutrients: [
      { name: 'C Vitamini', value: 65, unit: 'mg' },
      { name: 'Demir', value: 0.7, unit: 'mg' },
      { name: 'Kalsiyum', value: 40, unit: 'mg' },
    ],
    tip: 'İlk denemede bebeğiniz burun kıvırabilir, birkaç kez denemeye devam edin.',
    createdAt: hoursAgo(68),
  },
  {
    id: '38',
    title: 'Şeftalili Pirinç Püresi',
    description: 'Yazın mevsimindeki taze şeftali ile hafif pirinç püresi.',
    emoji: '🍑',
    ageGroup: '6m',
    prepTime: 15,
    calories: 75,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.7, count: 25 },
    likes: 130, views: 720, comments: 11,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Meyve', 'Pirinçli', 'Yazlık'],
    ingredients: [
      { name: 'Şeftali', amount: 1, unit: 'küçük', emoji: '🍑' },
      { name: 'Pirinç', amount: 1, unit: 'yemek kaşığı', emoji: '🍚' },
      { name: 'Su', amount: 150, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Pirinci yıkayıp tencereye alın.',
      'Su ekleyip kaynatın, kısık ateşte 10 dakika pişirin.',
      'Şeftaliyi soyup rendeleyerek pirincin üzerine ekleyin.',
      '2 dakika daha pişirip blenderdan geçirin.',
    ],
    nutrients: [
      { name: 'Karbonhidrat', value: 16, unit: 'g' },
      { name: 'C Vitamini', value: 5, unit: 'mg' },
      { name: 'Lif', value: 1.5, unit: 'g' },
    ],
    tip: 'Mevsiminde olmayan şeftali yerine kayısı kullanabilirsiniz.',
    createdAt: hoursAgo(69),
  },
  {
    id: '39',
    title: 'Tatlı Patates Püresi',
    description: 'Beta-karoten deposu, doğal tatlı bir süper besin.',
    emoji: '🍠',
    ageGroup: '6m',
    prepTime: 25,
    calories: 95,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.8, count: 33 },
    likes: 160, views: 920, comments: 16,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Sebze', 'Vitamin', 'Kolay'],
    ingredients: [
      { name: 'Tatlı Patates', amount: 1, unit: 'küçük', emoji: '🍠' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Tatlı patatesi soyup küçük küpler halinde doğrayın.',
      'Buharda 20 dakika pişirin.',
      'Çatalla iyice ezin.',
      'Zeytinyağı ekleyip karıştırın.',
    ],
    nutrients: [
      { name: 'A Vitamini', value: 960, unit: 'mcg' },
      { name: 'Karbonhidrat', value: 20, unit: 'g' },
      { name: 'Lif', value: 3, unit: 'g' },
    ],
    tip: 'Tatlı patates A vitamini şampiyonudur. Zeytinyağı ile birlikte emilim artar.',
    createdAt: hoursAgo(70),
  },
  {
    id: '40',
    title: 'Bezelyeli Patates Püresi',
    description: 'Protein ve lif açısından zengin, doyurucu bir karışım.',
    emoji: '🟢',
    ageGroup: '6m',
    prepTime: 18,
    calories: 85,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.5, count: 22 },
    likes: 110, views: 650, comments: 9,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Sebze', 'Proteinli', 'Doyurucu'],
    ingredients: [
      { name: 'Bezelye', amount: 3, unit: 'yemek kaşığı', emoji: '🟢' },
      { name: 'Patates', amount: 0.5, unit: 'küçük', emoji: '🥔' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
      { name: 'Su', amount: 100, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Patatesi soyup küçük doğrayın.',
      'Bezelye ve patateyi birlikte haşlayın.',
      '15 dakika pişirin.',
      'Blenderla pürüzsüz kıvama getirin.',
      'Zeytinyağı ekleyip servis edin.',
    ],
    nutrients: [
      { name: 'Protein', value: 3, unit: 'g' },
      { name: 'Lif', value: 3.5, unit: 'g' },
      { name: 'Demir', value: 1, unit: 'mg' },
    ],
    tip: 'Bezelye biraz gaz yapabilir. İlk başta az miktarda deneyin.',
    createdAt: hoursAgo(71),
  },
  {
    id: '41',
    title: 'Erikli Yulaf Püresi',
    description: 'Kabızlığa karşı etkili, lifli ve besleyici mama.',
    emoji: '🟣',
    ageGroup: '6m',
    prepTime: 12,
    calories: 70,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.6, count: 20 },
    likes: 100, views: 600, comments: 8,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat'],
    tags: ['Meyve', 'Yulaf', 'Lifli'],
    ingredients: [
      { name: 'Erik', amount: 2, unit: 'adet', emoji: '🟣' },
      { name: 'Yulaf ezmesi', amount: 1, unit: 'yemek kaşığı', emoji: '🌾', isAllergen: true },
      { name: 'Su', amount: 100, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Erikleri yıkayıp çekirdeklerini çıkarın.',
      'Yulaf ezmesi ve su ile tencereye alın.',
      'Kısık ateşte 10 dakika pişirin.',
      'Blenderla pürüzsüz kıvama getirin.',
    ],
    nutrients: [
      { name: 'Lif', value: 4, unit: 'g' },
      { name: 'Karbonhidrat', value: 14, unit: 'g' },
      { name: 'Demir', value: 0.5, unit: 'mg' },
    ],
    tip: 'Erik doğal müshildir. Kabızlık sorunu olan bebekler için idealdir.',
    createdAt: hoursAgo(72),
  },
  {
    id: '42',
    title: 'Ispanak-Patates Püresi',
    description: 'Demir deposu ıspanak ile doyurucu patates birlikteliği.',
    emoji: '🥬',
    ageGroup: '6m',
    prepTime: 18,
    calories: 75,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.5, count: 27 },
    likes: 125, views: 750, comments: 11,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Sebze', 'Demir', 'Doyurucu'],
    ingredients: [
      { name: 'Ispanak', amount: 5, unit: 'yaprak', emoji: '🥬' },
      { name: 'Patates', amount: 1, unit: 'küçük', emoji: '🥔' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Patatesi soyup haşlayın.',
      'Ispanakları yıkayıp son 3 dakikada ekleyin.',
      'Blenderla pürüzsüz kıvama getirin.',
      'Zeytinyağı ekleyin.',
    ],
    nutrients: [
      { name: 'Demir', value: 2, unit: 'mg' },
      { name: 'Kalsiyum', value: 55, unit: 'mg' },
      { name: 'A Vitamini', value: 300, unit: 'mcg' },
    ],
    tip: 'Ispanağın yanında C vitamini kaynağı (limon birkaç damla) eklemek demir emilimini artırır.',
    createdAt: hoursAgo(73),
  },
  {
    id: '43',
    title: 'Kayısılı Yulaf Lapası',
    description: 'Kurutulmuş kayısı ile yapılan, demir deposu kahvaltılık.',
    emoji: '🟠',
    ageGroup: '6m',
    prepTime: 10,
    calories: 80,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.7, count: 30 },
    likes: 145, views: 820, comments: 13,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat'],
    tags: ['Kahvaltı', 'Yulaf', 'Demir'],
    ingredients: [
      { name: 'Yulaf ezmesi', amount: 2, unit: 'yemek kaşığı', emoji: '🌾', isAllergen: true },
      { name: 'Kuru kayısı', amount: 2, unit: 'adet', emoji: '🟠' },
      { name: 'Su', amount: 150, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Kuru kayısıları sıcak suda 5 dakika bekletin.',
      'Yulaf ezmesi ve suyu tencereye alıp kaynatın.',
      'Kısık ateşte 5 dakika pişirin.',
      'Yumuşayan kayısıları ekleyip blenderdan geçirin.',
    ],
    nutrients: [
      { name: 'Demir', value: 1.5, unit: 'mg' },
      { name: 'Lif', value: 3, unit: 'g' },
      { name: 'Karbonhidrat', value: 16, unit: 'g' },
    ],
    tip: 'Kayısı demir açısından çok zengindir. Kansızlık riski olan bebekler için harika bir seçim.',
    createdAt: hoursAgo(74),
  },
  {
    id: '44',
    title: 'Havuç-Kabak-Pirinç Çorbası',
    description: 'Üç malzemeli hafif ve besleyici bebek çorbası.',
    emoji: '🍲',
    ageGroup: '6m',
    prepTime: 20,
    calories: 70,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.6, count: 26 },
    likes: 135, views: 760, comments: 12,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Çorba', 'Sebze', 'Hafif'],
    ingredients: [
      { name: 'Havuç', amount: 0.5, unit: 'adet', emoji: '🥕' },
      { name: 'Kabak', amount: 0.5, unit: 'küçük', emoji: '🎃' },
      { name: 'Pirinç', amount: 1, unit: 'yemek kaşığı', emoji: '🍚' },
      { name: 'Su', amount: 250, unit: 'ml', emoji: '💧' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Havuç ve kabağı soyup küçük küpler halinde doğrayın.',
      'Pirinci yıkayıp tencereye tüm malzemeleri ekleyin.',
      'Su ekleyip kaynatın.',
      'Kısık ateşte 20 dakika pişirin.',
      'Blenderla pürüzsüz kıvama getirip zeytinyağı ekleyin.',
    ],
    nutrients: [
      { name: 'Karbonhidrat', value: 14, unit: 'g' },
      { name: 'A Vitamini', value: 400, unit: 'mcg' },
      { name: 'Lif', value: 2, unit: 'g' },
    ],
    tip: 'Bu çorba soğuk havalarda bebeğinizi ısıtacak ve doyuracaktır.',
    createdAt: hoursAgo(75),
  },
  {
    id: '79',
    title: 'Elma Püresi',
    description: 'Tatlı ve hafif, mideye dost ilk meyve püresi.',
    emoji: '🍎',
    ageGroup: '6m',
    prepTime: 10,
    calories: 40,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.8, count: 52 },
    likes: 250, views: 1500, comments: 28,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Meyve', 'İlk Ek Gıda', 'Kolay'],
    ingredients: [
      { name: 'Elma', amount: 1, unit: 'orta boy', emoji: '🍎' },
      { name: 'Su', amount: 50, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Elmayı soyun ve çekirdeklerini çıkarın.',
      'Küçük parçalara bölün.',
      'Az suda 8-10 dakika buharda pişirin.',
      'Çatalla veya blenderla pürüzsüz kıvama getirin.',
      'Ilık olarak servis edin.',
    ],
    nutrients: [
      { name: 'C Vitamini', value: 8, unit: 'mg' },
      { name: 'Lif', value: 2, unit: 'g' },
      { name: 'Karbonhidrat', value: 10, unit: 'g' },
    ],
    tip: 'Ekşi elma tercih etmeyin, tatlı kırmızı elma idealdir.',
    createdAt: hoursAgo(110),
  },
  {
    id: '80',
    title: 'Balkabağı Püresi',
    description: 'A vitamini deposu, tatlı balkabağı püresi.',
    emoji: '🎃',
    ageGroup: '6m',
    prepTime: 20,
    calories: 50,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.7, count: 40 },
    likes: 200, views: 1200, comments: 20,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Sebze', 'İlk Ek Gıda', 'Mevsimsel'],
    ingredients: [
      { name: 'Balkabağı', amount: 100, unit: 'gram', emoji: '🎃' },
      { name: 'Su', amount: 50, unit: 'ml', emoji: '💧' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Balkabağını soyup küp küp doğrayın.',
      'Buharda 15 dakika yumuşayana kadar pişirin.',
      'Blenderla pürüzsüz hale getirin.',
      'Zeytinyağı ekleyip karıştırın.',
    ],
    nutrients: [
      { name: 'A Vitamini', value: 600, unit: 'mcg' },
      { name: 'C Vitamini', value: 9, unit: 'mg' },
      { name: 'Lif', value: 1.5, unit: 'g' },
    ],
    tip: 'Sonbahar aylarında taze balkabağı kolayca bulunur. Dondurmaya da uygundur.',
    createdAt: hoursAgo(111),
  },
  {
    id: '81',
    title: 'Pirinç Lapası',
    description: 'Yumuşak ve hafif, hassas mideli bebekler için pirinç lapası.',
    emoji: '🍚',
    ageGroup: '6m',
    prepTime: 15,
    calories: 55,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.5, count: 35 },
    likes: 170, views: 1000, comments: 15,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Tahıl', 'İlk Ek Gıda', 'Hafif'],
    ingredients: [
      { name: 'Pirinç unu', amount: 1, unit: 'yemek kaşığı', emoji: '🍚' },
      { name: 'Su', amount: 150, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Pirinç ununu soğuk suyla karıştırın.',
      'Kısık ateşte karıştırarak pişirin.',
      'Koyulaşınca ateşten alın.',
      'Ilık olarak servis edin.',
    ],
    nutrients: [
      { name: 'Karbonhidrat', value: 12, unit: 'g' },
      { name: 'Enerji', value: 55, unit: 'kcal' },
    ],
    tip: 'İshal dönemlerinde hafif bir besin olarak da tercih edilir.',
    createdAt: hoursAgo(112),
  },
  {
    id: '82',
    title: 'Kabak-Elma Püresi',
    description: 'Sebze ve meyve birleşimi, tatlı ve besleyici.',
    emoji: '🎃',
    ageGroup: '6m',
    prepTime: 15,
    calories: 50,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.6, count: 30 },
    likes: 150, views: 900, comments: 14,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Sebze', 'Meyve', 'Karma'],
    ingredients: [
      { name: 'Kabak', amount: 1, unit: 'küçük', emoji: '🎃' },
      { name: 'Elma', amount: 0.5, unit: 'adet', emoji: '🍎' },
      { name: 'Su', amount: 50, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Kabak ve elmayı soyup küçük parçalara doğrayın.',
      'Buharda 10-12 dakika pişirin.',
      'Blenderla pürüzsüz hale getirin.',
      'Ilık olarak servis edin.',
    ],
    nutrients: [
      { name: 'A Vitamini', value: 200, unit: 'mcg' },
      { name: 'C Vitamini', value: 6, unit: 'mg' },
      { name: 'Lif', value: 2, unit: 'g' },
    ],
    tip: 'Elma kabağın tadını tatlandırır, sebze sevmeyen bebekler için idealdir.',
    createdAt: hoursAgo(113),
  },
  {
    id: '83',
    title: 'Havuç-Portakal Püresi',
    description: 'C ve A vitamini deposu, bağışıklık güçlendirici.',
    emoji: '🥕',
    ageGroup: '6m',
    prepTime: 15,
    calories: 48,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.4, count: 28 },
    likes: 130, views: 800, comments: 12,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Sebze', 'Meyve', 'Bağışıklık'],
    ingredients: [
      { name: 'Havuç', amount: 1, unit: 'orta boy', emoji: '🥕' },
      { name: 'Portakal suyu', amount: 2, unit: 'yemek kaşığı', emoji: '🍊' },
      { name: 'Su', amount: 50, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Havucu soyup küçük parçalara doğrayın.',
      'Buharda 12-15 dakika pişirin.',
      'Blenderla püre yapın.',
      'Portakal suyunu ekleyip karıştırın.',
    ],
    nutrients: [
      { name: 'A Vitamini', value: 800, unit: 'mcg' },
      { name: 'C Vitamini', value: 20, unit: 'mg' },
      { name: 'Lif', value: 2.5, unit: 'g' },
    ],
    tip: 'Portakal suyu demir emilimini artırır. Taze sıkılmış tercih edin.',
    createdAt: hoursAgo(114),
  },
];

// =============================================
// 8+ AY EK TARİFLER
// =============================================

export const EXTRA_RECIPES_8M: RecipeData[] = [
  {
    id: '45',
    title: 'Mercimek Çorbası',
    description: 'Demir ve protein deposu, geleneksel Türk bebek çorbası.',
    emoji: '🍲',
    ageGroup: '8m',
    prepTime: 25,
    calories: 120,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.9, count: 50 },
    likes: 280, views: 1800, comments: 30,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Çorba', 'Demir', 'Protein'],
    ingredients: [
      { name: 'Kırmızı Mercimek', amount: 3, unit: 'yemek kaşığı', emoji: '🟠' },
      { name: 'Havuç', amount: 0.5, unit: 'adet', emoji: '🥕' },
      { name: 'Patates', amount: 0.5, unit: 'küçük', emoji: '🥔' },
      { name: 'Soğan', amount: 0.25, unit: 'adet', emoji: '🧅' },
      { name: 'Su', amount: 300, unit: 'ml', emoji: '💧' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Mercimeği yıkayın.',
      'Soğanı, havucu ve patatesi soyup minik doğrayın.',
      'Tüm malzemeleri tencereye alıp suyu ekleyin.',
      'Kaynadıktan sonra kısık ateşte 20 dakika pişirin.',
      'Blenderdan geçirip zeytinyağı ekleyin.',
    ],
    nutrients: [
      { name: 'Protein', value: 8, unit: 'g' },
      { name: 'Demir', value: 3, unit: 'mg' },
      { name: 'Lif', value: 4, unit: 'g' },
    ],
    tip: 'Mercimek Türk mutfağının en besleyici bakliyatlarındandır. Limon birkaç damla demir emilimini artırır.',
    createdAt: hoursAgo(76),
  },
  {
    id: '46',
    title: 'Sebzeli İrmik',
    description: 'Kabak, havuç ve ıspanakla zenginleştirilmiş irmik.',
    emoji: '🌾',
    ageGroup: '8m',
    prepTime: 15,
    calories: 110,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.6, count: 35 },
    likes: 165, views: 950, comments: 16,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat'],
    tags: ['İrmik', 'Sebze', 'Doyurucu'],
    ingredients: [
      { name: 'İrmik', amount: 2, unit: 'yemek kaşığı', emoji: '🌾', isAllergen: true },
      { name: 'Kabak', amount: 0.25, unit: 'adet', emoji: '🎃' },
      { name: 'Havuç', amount: 0.25, unit: 'adet', emoji: '🥕' },
      { name: 'Ispanak', amount: 3, unit: 'yaprak', emoji: '🥬' },
      { name: 'Su', amount: 200, unit: 'ml', emoji: '💧' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Kabak ve havucu rendeleyin.',
      'Tencereye suyu koyup sebzeleri ekleyin.',
      'Kaynadığında irmiği yavaşça ekleyip karıştırın.',
      'Ispanağı doğrayıp son 2 dakikada ekleyin.',
      'Kıvam alınca zeytinyağı ile servis edin.',
    ],
    nutrients: [
      { name: 'Karbonhidrat', value: 18, unit: 'g' },
      { name: 'Protein', value: 3, unit: 'g' },
      { name: 'Demir', value: 1.5, unit: 'mg' },
    ],
    tip: 'İrmiği eklerken sürekli karıştırın yoksa topaklanır.',
    createdAt: hoursAgo(77),
  },
  {
    id: '47',
    title: 'Kıymalı Patates',
    description: 'Demirli kıyma ile doyurucu patates yemeği.',
    emoji: '🥩',
    ageGroup: '8m',
    prepTime: 25,
    calories: 140,
    servings: 1,
    difficulty: 'medium',
    rating: { average: 4.7, count: 40 },
    likes: 200, views: 1100, comments: 20,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Etli', 'Demir', 'Doyurucu'],
    ingredients: [
      { name: 'Dana kıyma', amount: 2, unit: 'yemek kaşığı', emoji: '🥩' },
      { name: 'Patates', amount: 1, unit: 'küçük', emoji: '🥔' },
      { name: 'Havuç', amount: 0.5, unit: 'adet', emoji: '🥕' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
      { name: 'Su', amount: 200, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Kıymayı suda haşlayıp köpüklerini alın.',
      'Patates ve havucu soyup küçük doğrayın.',
      'Tüm malzemeleri tencereye alıp 20 dakika pişirin.',
      'Çatalla ezin veya blenderdan hafif geçirin.',
      'Zeytinyağı ekleyip servis edin.',
    ],
    nutrients: [
      { name: 'Protein', value: 10, unit: 'g' },
      { name: 'Demir', value: 2.5, unit: 'mg' },
      { name: 'Karbonhidrat', value: 15, unit: 'g' },
    ],
    tip: 'Kıymayı çift çekilmiş yağsız olarak tercih edin.',
    createdAt: hoursAgo(78),
  },
  {
    id: '48',
    title: 'Tavuklu Sebze Çorbası',
    description: 'Protein ve vitamin dolu, bağışıklık destekleyici çorba.',
    emoji: '🐔',
    ageGroup: '8m',
    prepTime: 30,
    calories: 130,
    servings: 1,
    difficulty: 'medium',
    rating: { average: 4.8, count: 42 },
    likes: 220, views: 1300, comments: 22,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Çorba', 'Tavuk', 'Bağışıklık'],
    ingredients: [
      { name: 'Tavuk göğsü', amount: 1, unit: 'küçük parça', emoji: '🐔' },
      { name: 'Havuç', amount: 0.5, unit: 'adet', emoji: '🥕' },
      { name: 'Patates', amount: 0.5, unit: 'küçük', emoji: '🥔' },
      { name: 'Kabak', amount: 0.25, unit: 'adet', emoji: '🎃' },
      { name: 'Pirinç', amount: 1, unit: 'yemek kaşığı', emoji: '🍚' },
      { name: 'Su', amount: 300, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Tavuğu haşlayıp didikleyin.',
      'Sebzeleri soyup küçük doğrayın.',
      'Pirinci yıkayıp tencereye tüm malzemeleri ekleyin.',
      'Kısık ateşte 25 dakika pişirin.',
      'Blenderdan geçirip ılık servis edin.',
    ],
    nutrients: [
      { name: 'Protein', value: 12, unit: 'g' },
      { name: 'Karbonhidrat', value: 14, unit: 'g' },
      { name: 'A Vitamini', value: 350, unit: 'mcg' },
    ],
    tip: 'Tavuk suyu bağışıklık sistemini destekler. Hastalandığında bu çorbayı sıklıkla verebilirsiniz.',
    createdAt: hoursAgo(79),
  },
  {
    id: '49',
    title: 'Yumurta Sarılı Havuç',
    description: '8. ayda başlanabilen yumurta sarısı ile besleyici tarif.',
    emoji: '🥚',
    ageGroup: '8m',
    prepTime: 15,
    calories: 100,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.5, count: 35 },
    likes: 170, views: 980, comments: 15,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['egg'],
    tags: ['Yumurta', 'Demir', 'Kolay'],
    ingredients: [
      { name: 'Yumurta', amount: 1, unit: 'adet (sarısı)', emoji: '🥚', isAllergen: true },
      { name: 'Havuç', amount: 1, unit: 'küçük', emoji: '🥕' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Yumurtayı haşlayıp sarısını ayırın.',
      'Havucu soyup buharda 12 dakika pişirin.',
      'Havucu çatalla ezin.',
      'Yumurta sarısını ekleyip iyice karıştırın.',
      'Zeytinyağı ile servis edin.',
    ],
    nutrients: [
      { name: 'Protein', value: 4, unit: 'g' },
      { name: 'Demir', value: 1.2, unit: 'mg' },
      { name: 'D Vitamini', value: 1, unit: 'mcg' },
    ],
    tip: 'Yumurta alerjisi şüphesi varsa çok az miktarla başlayıp 3 gün bekleyin.',
    createdAt: hoursAgo(80),
  },
  {
    id: '50',
    title: 'Bebek Pilavı',
    description: 'Tereyağlı, yumuşak bebek pilavı.',
    emoji: '🍚',
    ageGroup: '8m',
    prepTime: 20,
    calories: 100,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.4, count: 28 },
    likes: 130, views: 750, comments: 10,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['milk'],
    tags: ['Pirinç', 'Kolay', 'Doyurucu'],
    ingredients: [
      { name: 'Pirinç', amount: 3, unit: 'yemek kaşığı', emoji: '🍚' },
      { name: 'Su', amount: 200, unit: 'ml', emoji: '💧' },
      { name: 'Tereyağı', amount: 1, unit: 'çay kaşığı', emoji: '🧈', isAllergen: true },
    ],
    steps: [
      'Pirinci yıkayıp süzün.',
      'Tencereye su ekleyip kaynatın.',
      'Pirinci ekleyip kısık ateşte 15 dakika pişirin.',
      'Suyunu çekince tereyağı ekleyip karıştırın.',
      'Biraz ezik kıvamda servis edin.',
    ],
    nutrients: [
      { name: 'Karbonhidrat', value: 20, unit: 'g' },
      { name: 'Protein', value: 2, unit: 'g' },
      { name: 'Yağ', value: 3, unit: 'g' },
    ],
    tip: 'Yanına sebze püresi veya kıyma ekleyerek tam öğün yapabilirsiniz.',
    createdAt: hoursAgo(81),
  },
  {
    id: '51',
    title: 'Tarhana Çorbası',
    description: 'Geleneksel fermente tarhana ile yapılan bağışıklık çorbası.',
    emoji: '🥣',
    ageGroup: '8m',
    prepTime: 15,
    calories: 90,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.7, count: 38 },
    likes: 195, views: 1150, comments: 18,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat', 'milk'],
    tags: ['Çorba', 'Geleneksel', 'Fermente'],
    ingredients: [
      { name: 'Tarhana', amount: 2, unit: 'yemek kaşığı', emoji: '🟤', isAllergen: true },
      { name: 'Su', amount: 250, unit: 'ml', emoji: '💧' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Tarhanayı bir bardak soğuk suda eritin.',
      'Tencereye alıp kalan suyu ekleyin.',
      'Sürekli karıştırarak kaynatın.',
      'Kısık ateşte 10 dakika pişirin.',
      'Zeytinyağı ekleyip ılık servis edin.',
    ],
    nutrients: [
      { name: 'Protein', value: 4, unit: 'g' },
      { name: 'Karbonhidrat', value: 14, unit: 'g' },
      { name: 'Probiyotik', value: 1, unit: 'porsiyon' },
    ],
    tip: 'Tuzsuz, acısız ev tarhanası kullanın. Hazır tarhanalar genelde tuzludur.',
    createdAt: hoursAgo(82),
  },
  {
    id: '52',
    title: 'Kabak-Bezelye Püresi',
    description: 'Hafif ve lifli, sindirim dostu karışım.',
    emoji: '🟢',
    ageGroup: '8m',
    prepTime: 18,
    calories: 75,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.5, count: 22 },
    likes: 105, views: 620, comments: 9,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Sebze', 'Lifli', 'Hafif'],
    ingredients: [
      { name: 'Kabak', amount: 0.5, unit: 'orta boy', emoji: '🎃' },
      { name: 'Bezelye', amount: 3, unit: 'yemek kaşığı', emoji: '🟢' },
      { name: 'Havuç', amount: 0.25, unit: 'adet', emoji: '🥕' },
      { name: 'Kıyma', amount: 1, unit: 'yemek kaşığı', emoji: '🥩' },
      { name: 'Su', amount: 150, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Kabak ve havucu soyup küçük doğrayın.',
      'Bezelye ile birlikte tencereye alın.',
      'Kıymayı ayrı suda haşlayıp ekleyin.',
      'Su ekleyip 15 dakika pişirin.',
      'Bebeğinizin kıvamına göre blenderdan geçirin.',
    ],
    nutrients: [
      { name: 'Protein', value: 6, unit: 'g' },
      { name: 'Lif', value: 3, unit: 'g' },
      { name: 'Demir', value: 1.5, unit: 'mg' },
    ],
    tip: 'Pütürlü kıvama alışan bebekler için blenderdan geçirmeden verebilirsiniz.',
    createdAt: hoursAgo(83),
  },
  {
    id: '53',
    title: 'Peynirli Makarna',
    description: 'Parmak yiyecek olarak mükemmel, yumuşak peynirli makarna.',
    emoji: '🧀',
    ageGroup: '8m',
    prepTime: 15,
    calories: 130,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.8, count: 45 },
    likes: 240, views: 1400, comments: 25,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat', 'milk'],
    tags: ['Makarna', 'Parmak Yiyecek', 'Peynirli'],
    ingredients: [
      { name: 'Bebek makarnası', amount: 3, unit: 'yemek kaşığı', emoji: '🍝', isAllergen: true },
      { name: 'Lor peyniri', amount: 1, unit: 'yemek kaşığı', emoji: '🧀', isAllergen: true },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Makarnayı yumuşak olana kadar haşlayın.',
      'Süzüp soğumaya bırakın.',
      'Lor peyniri ve zeytinyağı ekleyip karıştırın.',
      'Bebeğin eliyle tutabileceği şekilde servis edin.',
    ],
    nutrients: [
      { name: 'Karbonhidrat', value: 18, unit: 'g' },
      { name: 'Protein', value: 5, unit: 'g' },
      { name: 'Kalsiyum', value: 50, unit: 'mg' },
    ],
    tip: 'Bebek makarnası yerine yıldız şehriye de kullanabilirsiniz.',
    createdAt: hoursAgo(84),
  },
  {
    id: '54',
    title: 'Fırında Sebze Çubukları',
    description: 'BLW için ideal, parmak uzunluğunda fırın sebzeleri.',
    emoji: '🥕',
    ageGroup: '8m',
    prepTime: 30,
    calories: 60,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.6, count: 30 },
    likes: 155, views: 870, comments: 14,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['BLW', 'Parmak Yiyecek', 'Fırın'],
    ingredients: [
      { name: 'Havuç', amount: 1, unit: 'adet', emoji: '🥕' },
      { name: 'Tatlı patates', amount: 0.5, unit: 'adet', emoji: '🍠' },
      { name: 'Kabak', amount: 0.5, unit: 'adet', emoji: '🎃' },
      { name: 'Zeytinyağı', amount: 2, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Fırını 180°C\'ye ısıtın.',
      'Sebzeleri parmak uzunluğunda çubuklar halinde kesin.',
      'Zeytinyağı ile yağlayın.',
      'Fırın tepsisine dizin.',
      '25-30 dakika yumuşayana kadar pişirin.',
    ],
    nutrients: [
      { name: 'A Vitamini', value: 500, unit: 'mcg' },
      { name: 'Lif', value: 3, unit: 'g' },
      { name: 'C Vitamini', value: 15, unit: 'mg' },
    ],
    tip: 'Sebzeler parmaklar arasında kolayca ezilecek kadar yumuşak olmalı.',
    createdAt: hoursAgo(85),
  },
  {
    id: '55',
    title: 'Muzlu Yulaf Pankek',
    description: 'İki malzemeli, kolay ve besleyici bebek pankeki.',
    emoji: '🥞',
    ageGroup: '8m',
    prepTime: 15,
    calories: 110,
    servings: 4,
    difficulty: 'easy',
    rating: { average: 4.9, count: 55 },
    likes: 300, views: 2000, comments: 35,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['egg', 'wheat'],
    tags: ['Kahvaltı', 'Parmak Yiyecek', 'Pratik'],
    ingredients: [
      { name: 'Muz', amount: 1, unit: 'olgun', emoji: '🍌' },
      { name: 'Yumurta', amount: 1, unit: 'adet', emoji: '🥚', isAllergen: true },
      { name: 'Yulaf unu', amount: 3, unit: 'yemek kaşığı', emoji: '🌾', isAllergen: true },
    ],
    steps: [
      'Muzu çatalla iyice ezin.',
      'Yumurtayı ekleyip çırpın.',
      'Yulaf ununu ekleyip karıştırın.',
      'Yapışmaz tavada az yağla mini pankekcikler yapın.',
      'Her iki tarafı 2 dakika pişirin.',
    ],
    nutrients: [
      { name: 'Protein', value: 5, unit: 'g' },
      { name: 'Karbonhidrat', value: 18, unit: 'g' },
      { name: 'Potasyum', value: 200, unit: 'mg' },
    ],
    tip: 'Çok olgun muz kullanın, doğal tatlılık sağlar. Dondurucuda saklanabilir.',
    createdAt: hoursAgo(86),
  },
  {
    id: '56',
    title: 'Bulgurlu Köfte',
    description: 'İnce bulgur ve kıyma ile yapılan yumuşak bebek köftesi.',
    emoji: '🧆',
    ageGroup: '8m',
    prepTime: 25,
    calories: 135,
    servings: 6,
    difficulty: 'medium',
    rating: { average: 4.7, count: 35 },
    likes: 185, views: 1050, comments: 18,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat'],
    tags: ['Etli', 'Parmak Yiyecek', 'Doyurucu'],
    ingredients: [
      { name: 'Dana kıyma', amount: 3, unit: 'yemek kaşığı', emoji: '🥩' },
      { name: 'İnce bulgur', amount: 2, unit: 'yemek kaşığı', emoji: '🌾', isAllergen: true },
      { name: 'Soğan', amount: 0.25, unit: 'adet (rendelenmiş)', emoji: '🧅' },
      { name: 'Maydanoz', amount: 1, unit: 'dal', emoji: '🌿' },
    ],
    steps: [
      'Bulguru ıslatıp süzün.',
      'Kıyma, bulgur, rendelenmiş soğan ve doğranmış maydanozu yoğurun.',
      'Minik yuvarlak köfteler şekillendirin.',
      'Buharda 20 dakika veya fırında 180°C\'de 15 dakika pişirin.',
    ],
    nutrients: [
      { name: 'Protein', value: 9, unit: 'g' },
      { name: 'Demir', value: 2, unit: 'mg' },
      { name: 'Karbonhidrat', value: 12, unit: 'g' },
    ],
    tip: 'Köfteleri dondurucuda saklayıp gerektiğinde çözebilirsiniz.',
    createdAt: hoursAgo(87),
  },
  {
    id: '57',
    title: 'Yoğurtlu Sebze Salatası',
    description: 'Pişmiş sebzelerle yapılan hafif yoğurtlu salata.',
    emoji: '🥗',
    ageGroup: '8m',
    prepTime: 20,
    calories: 80,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.4, count: 25 },
    likes: 115, views: 680, comments: 10,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['milk'],
    tags: ['Sebze', 'Yoğurtlu', 'Hafif'],
    ingredients: [
      { name: 'Havuç', amount: 1, unit: 'küçük', emoji: '🥕' },
      { name: 'Kabak', amount: 0.5, unit: 'küçük', emoji: '🎃' },
      { name: 'Brokoli', amount: 2, unit: 'çiçek', emoji: '🥦' },
      { name: 'Yoğurt', amount: 2, unit: 'yemek kaşığı', emoji: '🥛', isAllergen: true },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Sebzeleri buharda 12-15 dakika pişirin.',
      'Soğumaya bırakın.',
      'Küçük parçalara doğrayın veya çatalla hafifçe ezin.',
      'Yoğurt ve zeytinyağı ekleyip karıştırın.',
    ],
    nutrients: [
      { name: 'Protein', value: 3, unit: 'g' },
      { name: 'Kalsiyum', value: 60, unit: 'mg' },
      { name: 'C Vitamini', value: 30, unit: 'mg' },
    ],
    tip: 'Sebzeleri bebeğin çiğneyebileceği kadar yumuşak pişirin.',
    createdAt: hoursAgo(88),
  },
  {
    id: '58',
    title: 'Avokado-Muz Ezmesi',
    description: 'Sağlıklı yağlar ve potasyum dolu süper ikili.',
    emoji: '🥑',
    ageGroup: '8m',
    prepTime: 5,
    calories: 120,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.8, count: 40 },
    likes: 210, views: 1250, comments: 20,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Meyve', 'Pişirmesiz', 'Omega'],
    ingredients: [
      { name: 'Avokado', amount: 0.25, unit: 'adet', emoji: '🥑' },
      { name: 'Muz', amount: 0.5, unit: 'adet', emoji: '🍌' },
    ],
    steps: [
      'Avokadoyu ikiye bölüp çekirdeğini çıkarın.',
      'Muzu soyun.',
      'İkisini birlikte çatalla iyice ezin.',
      'Pürüzsüz kıvama gelince servis edin.',
    ],
    nutrients: [
      { name: 'Sağlıklı Yağ', value: 7, unit: 'g' },
      { name: 'Potasyum', value: 350, unit: 'mg' },
      { name: 'Lif', value: 3, unit: 'g' },
    ],
    tip: 'Avokado çok hızlı kararır. Hazırladıktan hemen sonra yedirin.',
    createdAt: hoursAgo(89),
  },
  {
    id: '59',
    title: 'Balkabaklı Risotto',
    description: 'İtalyan esintili, kremalı balkabağı risottosu.',
    emoji: '🎃',
    ageGroup: '8m',
    prepTime: 25,
    calories: 115,
    servings: 1,
    difficulty: 'medium',
    rating: { average: 4.6, count: 28 },
    likes: 145, views: 830, comments: 12,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['milk'],
    tags: ['Pirinç', 'Sebze', 'Özel'],
    ingredients: [
      { name: 'Pirinç', amount: 3, unit: 'yemek kaşığı', emoji: '🍚' },
      { name: 'Bal kabağı', amount: 2, unit: 'yemek kaşığı (püresi)', emoji: '🎃' },
      { name: 'Tereyağı', amount: 1, unit: 'çay kaşığı', emoji: '🧈', isAllergen: true },
      { name: 'Su', amount: 250, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Pirinci yıkayıp tencereye alın.',
      'Su ekleyip kaynatın, kısık ateşte pişirin.',
      'Pirinç yarı piştikten sonra kabak püresini ekleyin.',
      'Karıştırarak 10 dakika daha pişirin.',
      'Tereyağı ekleyip servis edin.',
    ],
    nutrients: [
      { name: 'Karbonhidrat', value: 20, unit: 'g' },
      { name: 'A Vitamini', value: 400, unit: 'mcg' },
      { name: 'Protein', value: 2, unit: 'g' },
    ],
    tip: 'Bal kabağı yerine tatlı patates püresi de kullanılabilir.',
    createdAt: hoursAgo(90),
  },
  {
    id: '84',
    title: 'Tavuklu Pirinç Çorbası',
    description: 'Protein ve enerji dolu, hafif ve besleyici çorba.',
    emoji: '🍲',
    ageGroup: '8m',
    prepTime: 25,
    calories: 90,
    servings: 2,
    difficulty: 'easy',
    rating: { average: 4.7, count: 42 },
    likes: 220, views: 1400, comments: 25,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Çorba', 'Tavuk', 'Pirinç'],
    ingredients: [
      { name: 'Tavuk göğsü', amount: 30, unit: 'gram', emoji: '🐔' },
      { name: 'Pirinç', amount: 1, unit: 'yemek kaşığı', emoji: '🍚' },
      { name: 'Havuç', amount: 0.5, unit: 'küçük', emoji: '🥕' },
      { name: 'Su', amount: 300, unit: 'ml', emoji: '💧' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Tavuğu suda haşlayıp didikleyin.',
      'Pirinci yıkayıp tavuk suyuna ekleyin.',
      'Havucu rendeleyip ekleyin.',
      'Kısık ateşte 15 dakika pişirin.',
      'Zeytinyağı ekleyip blenderdan geçirin veya çatalla ezin.',
    ],
    nutrients: [
      { name: 'Protein', value: 8, unit: 'g' },
      { name: 'Karbonhidrat', value: 10, unit: 'g' },
      { name: 'A Vitamini', value: 200, unit: 'mcg' },
    ],
    tip: 'Hastalık dönemlerinde ideal iyileştirici çorba.',
    createdAt: hoursAgo(115),
  },
  {
    id: '85',
    title: 'Yoğurtlu Ispanak',
    description: 'Demir ve kalsiyum kaynağı, yoğurtlu ıspanak ezmesi.',
    emoji: '🥬',
    ageGroup: '8m',
    prepTime: 15,
    calories: 65,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.5, count: 30 },
    likes: 160, views: 950, comments: 16,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['milk'],
    tags: ['Sebze', 'Yoğurt', 'Demir'],
    ingredients: [
      { name: 'Ispanak', amount: 1, unit: 'avuç', emoji: '🥬' },
      { name: 'Yoğurt', amount: 2, unit: 'yemek kaşığı', emoji: '🥛', isAllergen: true },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Ispanağı iyice yıkayın.',
      'Buharda 5 dakika pişirin.',
      'İnce kıyın veya blenderdan geçirin.',
      'Yoğurt ve zeytinyağı ekleyip karıştırın.',
    ],
    nutrients: [
      { name: 'Demir', value: 3, unit: 'mg' },
      { name: 'Kalsiyum', value: 120, unit: 'mg' },
      { name: 'K Vitamini', value: 300, unit: 'mcg' },
    ],
    tip: 'Ispanaktaki demir emilimini artırmak için yanında C vitamini kaynağı verin.',
    createdAt: hoursAgo(116),
  },
  {
    id: '86',
    title: 'Patatesli Havuç Çorbası',
    description: 'Kıvamlı ve doyurucu, iki sebzenin uyumu.',
    emoji: '🥣',
    ageGroup: '8m',
    prepTime: 20,
    calories: 70,
    servings: 2,
    difficulty: 'easy',
    rating: { average: 4.6, count: 35 },
    likes: 180, views: 1100, comments: 18,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Çorba', 'Sebze', 'Kolay'],
    ingredients: [
      { name: 'Patates', amount: 1, unit: 'küçük', emoji: '🥔' },
      { name: 'Havuç', amount: 1, unit: 'orta boy', emoji: '🥕' },
      { name: 'Su', amount: 250, unit: 'ml', emoji: '💧' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Patates ve havucu soyup küçük doğrayın.',
      'Su ile tencereye alıp kaynatın.',
      'Kısık ateşte 15 dakika pişirin.',
      'Blenderla pürüzsüz hale getirin.',
      'Zeytinyağı ekleyip servis edin.',
    ],
    nutrients: [
      { name: 'A Vitamini', value: 500, unit: 'mcg' },
      { name: 'Karbonhidrat', value: 15, unit: 'g' },
      { name: 'C Vitamini', value: 10, unit: 'mg' },
    ],
    tip: 'Dondurucuda buzluk poşetlerinde porsiyon porsiyon saklanabilir.',
    createdAt: hoursAgo(117),
  },
  {
    id: '87',
    title: 'Bebekler İçin Muhallebi',
    description: 'Sütlü, hafif ve besleyici şekersiz muhallebi.',
    emoji: '🍮',
    ageGroup: '8m',
    prepTime: 15,
    calories: 80,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.8, count: 45 },
    likes: 250, views: 1500, comments: 28,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['milk'],
    tags: ['Tatlı', 'Süt', 'Kolay'],
    ingredients: [
      { name: 'Süt', amount: 150, unit: 'ml', emoji: '🥛', isAllergen: true },
      { name: 'İrmik', amount: 1, unit: 'yemek kaşığı', emoji: '🌾' },
      { name: 'Muz', amount: 0.5, unit: 'adet', emoji: '🍌' },
    ],
    steps: [
      'Sütü tencereye alıp ısıtın.',
      'İrmiği karıştırarak ekleyin.',
      'Kısık ateşte 5-7 dakika pişirin.',
      'Muzu ezip karışıma katın.',
      'Kaselerine dökün, soğumaya bırakın.',
    ],
    nutrients: [
      { name: 'Kalsiyum', value: 150, unit: 'mg' },
      { name: 'Protein', value: 5, unit: 'g' },
      { name: 'Potasyum', value: 200, unit: 'mg' },
    ],
    tip: 'Muz doğal tatlandırıcıdır, şeker eklemeyin.',
    createdAt: hoursAgo(118),
  },
  {
    id: '88',
    title: 'Sebzeli Yulaf Çorbası',
    description: 'Lif bakımından zengin, doyurucu yulaf çorbası.',
    emoji: '🥣',
    ageGroup: '8m',
    prepTime: 20,
    calories: 75,
    servings: 2,
    difficulty: 'easy',
    rating: { average: 4.5, count: 28 },
    likes: 140, views: 850, comments: 14,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat'],
    tags: ['Çorba', 'Yulaf', 'Lif'],
    ingredients: [
      { name: 'Yulaf ezmesi', amount: 2, unit: 'yemek kaşığı', emoji: '🌾', isAllergen: true },
      { name: 'Kabak', amount: 0.5, unit: 'küçük', emoji: '🎃' },
      { name: 'Havuç', amount: 0.5, unit: 'küçük', emoji: '🥕' },
      { name: 'Su', amount: 250, unit: 'ml', emoji: '💧' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Sebzeleri küçük doğrayıp suda pişirin.',
      'Yumuşayınca yulaf ezmesini ekleyin.',
      'Kısık ateşte 10 dakika karıştırarak pişirin.',
      'Blenderdan geçirin, zeytinyağı ekleyin.',
    ],
    nutrients: [
      { name: 'Lif', value: 3, unit: 'g' },
      { name: 'Protein', value: 3, unit: 'g' },
      { name: 'Karbonhidrat', value: 12, unit: 'g' },
    ],
    tip: 'Kabızlık sorununa yardımcı olur. Yulaf beta-glukan kaynağıdır.',
    createdAt: hoursAgo(119),
  },
  {
    id: '89',
    title: 'Elmalı Yulaf Lapası',
    description: 'Kahvaltıya uygun, enerjik ve lifli lapa.',
    emoji: '🍎',
    ageGroup: '8m',
    prepTime: 10,
    calories: 85,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.7, count: 38 },
    likes: 200, views: 1200, comments: 20,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat'],
    tags: ['Kahvaltı', 'Yulaf', 'Meyve'],
    ingredients: [
      { name: 'Yulaf ezmesi', amount: 2, unit: 'yemek kaşığı', emoji: '🌾', isAllergen: true },
      { name: 'Elma', amount: 0.5, unit: 'adet (rendelenmiş)', emoji: '🍎' },
      { name: 'Su', amount: 100, unit: 'ml', emoji: '💧' },
      { name: 'Tarçın', amount: 1, unit: 'fiske', emoji: '🤎' },
    ],
    steps: [
      'Yulafı suyla tencereye alın.',
      'Rendelenmiş elmayı ekleyin.',
      'Kısık ateşte 7-8 dakika karıştırarak pişirin.',
      'Tarçın serpip ılık servis edin.',
    ],
    nutrients: [
      { name: 'Lif', value: 3.5, unit: 'g' },
      { name: 'Karbonhidrat', value: 16, unit: 'g' },
      { name: 'C Vitamini', value: 4, unit: 'mg' },
    ],
    tip: '8 aydan önce tarçın vermeyin. Çok az miktarda lezzet için yeterlidir.',
    createdAt: hoursAgo(120),
  },
  {
    id: '90',
    title: 'Patates-Brokoli Püresi',
    description: 'C vitamini ve potasyum kaynağı, doyurucu püre.',
    emoji: '🥦',
    ageGroup: '8m',
    prepTime: 18,
    calories: 75,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.6, count: 32 },
    likes: 170, views: 1000, comments: 15,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Sebze', 'Püre', 'Besleyici'],
    ingredients: [
      { name: 'Patates', amount: 1, unit: 'küçük', emoji: '🥔' },
      { name: 'Brokoli', amount: 3, unit: 'çiçek', emoji: '🥦' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
      { name: 'Su', amount: 50, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Patatesi soyup küçük doğrayın.',
      'Brokoli çiçekleriyle birlikte buharda 12 dakika pişirin.',
      'Çatalla iyice ezin veya blenderdan geçirin.',
      'Zeytinyağı ekleyip karıştırın.',
    ],
    nutrients: [
      { name: 'C Vitamini', value: 45, unit: 'mg' },
      { name: 'Potasyum', value: 350, unit: 'mg' },
      { name: 'Lif', value: 2.5, unit: 'g' },
    ],
    tip: 'Brokoli çok pişirilmemeli, yeşil rengini korumalıdır.',
    createdAt: hoursAgo(121),
  },
  {
    id: '91',
    title: 'Dana Etli Sebze Püresi',
    description: 'Demir açısından zengin, kırmızı etli sebze karışımı.',
    emoji: '🥩',
    ageGroup: '8m',
    prepTime: 30,
    calories: 110,
    servings: 1,
    difficulty: 'medium',
    rating: { average: 4.8, count: 40 },
    likes: 220, views: 1300, comments: 22,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Etli', 'Sebze', 'Demir'],
    ingredients: [
      { name: 'Dana kuşbaşı', amount: 30, unit: 'gram', emoji: '🥩' },
      { name: 'Patates', amount: 1, unit: 'küçük', emoji: '🥔' },
      { name: 'Havuç', amount: 0.5, unit: 'küçük', emoji: '🥕' },
      { name: 'Bezelye', amount: 1, unit: 'yemek kaşığı', emoji: '🟢' },
      { name: 'Su', amount: 200, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Dana etini küçük parçalara kesin, suda haşlayın.',
      'İlk suyu dökün, temiz su ekleyip 20 dakika daha pişirin.',
      'Sebzeleri ekleyip 10 dakika daha pişirin.',
      'Hepsini blenderla püre yapın.',
    ],
    nutrients: [
      { name: 'Demir', value: 4, unit: 'mg' },
      { name: 'Protein', value: 10, unit: 'g' },
      { name: 'Çinko', value: 2, unit: 'mg' },
    ],
    tip: 'Haftada 2-3 kez kırmızı et vermek demir ihtiyacını karşılar.',
    createdAt: hoursAgo(122),
  },
  {
    id: '92',
    title: 'Yoğurtlu Meyve Ezmesi',
    description: 'Mevsim meyveli probiyotik atıştırmalık.',
    emoji: '🍓',
    ageGroup: '8m',
    prepTime: 5,
    calories: 70,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.9, count: 55 },
    likes: 300, views: 2000, comments: 35,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['milk'],
    tags: ['Meyve', 'Yoğurt', 'Atıştırmalık'],
    ingredients: [
      { name: 'Yoğurt', amount: 3, unit: 'yemek kaşığı', emoji: '🥛', isAllergen: true },
      { name: 'Muz', amount: 0.5, unit: 'adet', emoji: '🍌' },
      { name: 'Çilek', amount: 2, unit: 'adet', emoji: '🍓' },
    ],
    steps: [
      'Muzu çatalla iyice ezin.',
      'Çilekleri minik parçalara doğrayın.',
      'Yoğurda ekleyip karıştırın.',
      'Hemen servis edin.',
    ],
    nutrients: [
      { name: 'Kalsiyum', value: 100, unit: 'mg' },
      { name: 'C Vitamini', value: 15, unit: 'mg' },
      { name: 'Probiyotik', value: 1, unit: 'porsiyon' },
    ],
    tip: 'Mevsime göre şeftali, kayısı, böğürtlen de kullanılabilir.',
    createdAt: hoursAgo(123),
  },
];

// =============================================
// 12+ AY EK TARİFLER
// =============================================

export const EXTRA_RECIPES_12M: RecipeData[] = [
  {
    id: '60',
    title: 'Tavuklu Sebze Pilav',
    description: 'Aile sofrasından bebek versiyonu, tek tencere tam öğün.',
    emoji: '🍗',
    ageGroup: '12m+',
    prepTime: 30,
    calories: 180,
    servings: 1,
    difficulty: 'medium',
    rating: { average: 4.8, count: 45 },
    likes: 250, views: 1500, comments: 28,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Etli', 'Tam Öğün', 'Aile'],
    ingredients: [
      { name: 'Tavuk budu', amount: 1, unit: 'küçük', emoji: '🍗' },
      { name: 'Pirinç', amount: 3, unit: 'yemek kaşığı', emoji: '🍚' },
      { name: 'Havuç', amount: 0.5, unit: 'adet', emoji: '🥕' },
      { name: 'Bezelye', amount: 2, unit: 'yemek kaşığı', emoji: '🟢' },
      { name: 'Zeytinyağı', amount: 1, unit: 'yemek kaşığı', emoji: '🫒' },
      { name: 'Su', amount: 300, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Tavuğu haşlayıp didikleyin.',
      'Havucu küçük küpler halinde doğrayın.',
      'Pirinci yıkayıp tencereye zeytinyağıyla kavurun.',
      'Havuç, bezelye ve didiklenmiş tavuğu ekleyin.',
      'Su ekleyip kısık ateşte 20 dakika pişirin.',
    ],
    nutrients: [
      { name: 'Protein', value: 15, unit: 'g' },
      { name: 'Karbonhidrat', value: 22, unit: 'g' },
      { name: 'Demir', value: 2, unit: 'mg' },
    ],
    tip: 'Tüm aile için porsiyonu büyütüp birlikte yiyebilirsiniz — tuzsuz pişirin.',
    createdAt: hoursAgo(91),
  },
  {
    id: '61',
    title: 'Fırında Balık Lokmaları',
    description: 'Omega-3 dolu, çıtır dışı yumuşak içli balık lokmaları.',
    emoji: '🐟',
    ageGroup: '12m+',
    prepTime: 25,
    calories: 150,
    servings: 6,
    difficulty: 'medium',
    rating: { average: 4.7, count: 35 },
    likes: 190, views: 1100, comments: 20,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['fish', 'wheat', 'egg'],
    tags: ['Balık', 'Omega-3', 'Fırın'],
    ingredients: [
      { name: 'Somon fileto', amount: 100, unit: 'gram', emoji: '🐟', isAllergen: true },
      { name: 'Galeta unu', amount: 2, unit: 'yemek kaşığı', emoji: '🍞', isAllergen: true },
      { name: 'Yumurta', amount: 1, unit: 'adet', emoji: '🥚', isAllergen: true },
      { name: 'Zeytinyağı', amount: 1, unit: 'yemek kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Fırını 190°C\'ye ısıtın.',
      'Somonu küçük lokma boyutunda parçalara bölün.',
      'Yumurtayı çırpıp balıkları geçirin.',
      'Galeta ununa bulayın.',
      'Yağlanmış tepsiye dizin, 15-20 dakika pişirin.',
    ],
    nutrients: [
      { name: 'Protein', value: 16, unit: 'g' },
      { name: 'Omega-3', value: 1.2, unit: 'g' },
      { name: 'D Vitamini', value: 5, unit: 'mcg' },
    ],
    tip: 'Haftada 1-2 kez balık vermek beyin gelişimi için çok önemlidir.',
    createdAt: hoursAgo(92),
  },
  {
    id: '62',
    title: 'Sebzeli Makarna',
    description: 'Renkli sebzelerle dolu, eğlenceli ve besleyici makarna.',
    emoji: '🍝',
    ageGroup: '12m+',
    prepTime: 20,
    calories: 160,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.8, count: 50 },
    likes: 270, views: 1700, comments: 30,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat'],
    tags: ['Makarna', 'Sebze', 'Kolay'],
    ingredients: [
      { name: 'Fiyonk makarna', amount: 4, unit: 'yemek kaşığı', emoji: '🍝', isAllergen: true },
      { name: 'Brokoli', amount: 2, unit: 'çiçek', emoji: '🥦' },
      { name: 'Havuç', amount: 0.5, unit: 'küçük', emoji: '🥕' },
      { name: 'Domates', amount: 0.5, unit: 'adet', emoji: '🍅' },
      { name: 'Zeytinyağı', amount: 1, unit: 'yemek kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Makarnayı yumuşak olana kadar haşlayın.',
      'Havucu küçük küpler halinde, brokoliyi çiçeklerine ayırıp haşlayın.',
      'Domatesi soyup küçük doğrayın.',
      'Hepsini süzüp karıştırın.',
      'Zeytinyağı ile servis edin.',
    ],
    nutrients: [
      { name: 'Karbonhidrat', value: 25, unit: 'g' },
      { name: 'Protein', value: 5, unit: 'g' },
      { name: 'C Vitamini', value: 35, unit: 'mg' },
    ],
    tip: 'Farklı şekilli makarnalar bebeğin ilgisini çeker ve yemek eğlenceli hale gelir.',
    createdAt: hoursAgo(93),
  },
  {
    id: '63',
    title: 'Somonlu Köfte',
    description: 'Balık sevmeyen bebekler için gizli somon köftesi.',
    emoji: '🐟',
    ageGroup: '12m+',
    prepTime: 25,
    calories: 145,
    servings: 6,
    difficulty: 'medium',
    rating: { average: 4.6, count: 30 },
    likes: 160, views: 920, comments: 15,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['fish', 'egg'],
    tags: ['Balık', 'Köfte', 'Omega-3'],
    ingredients: [
      { name: 'Somon', amount: 100, unit: 'gram', emoji: '🐟', isAllergen: true },
      { name: 'Patates', amount: 1, unit: 'küçük (haşlanmış)', emoji: '🥔' },
      { name: 'Yumurta', amount: 0.5, unit: 'adet', emoji: '🥚', isAllergen: true },
      { name: 'Dereotu', amount: 1, unit: 'dal', emoji: '🌿' },
    ],
    steps: [
      'Somonu buharda pişirip çatalla parçalayın.',
      'Haşlanmış patatesi ezin.',
      'Tüm malzemeleri karıştırıp yoğurun.',
      'Minik köfteler şekillendirin.',
      'Fırında 180°C\'de 15 dakika pişirin.',
    ],
    nutrients: [
      { name: 'Protein', value: 14, unit: 'g' },
      { name: 'Omega-3', value: 1, unit: 'g' },
      { name: 'D Vitamini', value: 4, unit: 'mcg' },
    ],
    tip: 'Dondurucuda 2 aya kadar saklanabilir. Çözdükten sonra tekrar dondurmayın.',
    createdAt: hoursAgo(94),
  },
  {
    id: '64',
    title: 'Ispanaklı Krep',
    description: 'Yeşil renkli eğlenceli krep, ıspanağı sevdirir.',
    emoji: '🥬',
    ageGroup: '12m+',
    prepTime: 20,
    calories: 120,
    servings: 4,
    difficulty: 'medium',
    rating: { average: 4.7, count: 38 },
    likes: 200, views: 1200, comments: 22,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat', 'egg', 'milk'],
    tags: ['Kahvaltı', 'Ispanak', 'Eğlenceli'],
    ingredients: [
      { name: 'Un', amount: 4, unit: 'yemek kaşığı', emoji: '🌾', isAllergen: true },
      { name: 'Yumurta', amount: 1, unit: 'adet', emoji: '🥚', isAllergen: true },
      { name: 'Süt', amount: 100, unit: 'ml', emoji: '🥛', isAllergen: true },
      { name: 'Ispanak', amount: 5, unit: 'yaprak', emoji: '🥬' },
    ],
    steps: [
      'Ispanakları yıkayıp blenderda sütle birlikte çekin.',
      'Un ve yumurta ekleyip pürüzsüz hamur yapın.',
      'Yapışmaz tavada ince krepler pişirin.',
      'Her iki tarafı 1-2 dakika pişirin.',
      'Rulo yapıp parmak yiyecek olarak servis edin.',
    ],
    nutrients: [
      { name: 'Protein', value: 5, unit: 'g' },
      { name: 'Demir', value: 2, unit: 'mg' },
      { name: 'Kalsiyum', value: 70, unit: 'mg' },
    ],
    tip: 'İçine lor peyniri sararak daha besleyici hale getirebilirsiniz.',
    createdAt: hoursAgo(95),
  },
  {
    id: '65',
    title: 'Nohutlu Pirinç Pilavı',
    description: 'Bitkisel protein kaynağı, doyurucu nohutlu pilav.',
    emoji: '🫘',
    ageGroup: '12m+',
    prepTime: 25,
    calories: 155,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.5, count: 25 },
    likes: 130, views: 780, comments: 12,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Bakliyat', 'Pirinç', 'Proteinli'],
    ingredients: [
      { name: 'Pirinç', amount: 3, unit: 'yemek kaşığı', emoji: '🍚' },
      { name: 'Nohut', amount: 2, unit: 'yemek kaşığı (haşlanmış)', emoji: '🫘' },
      { name: 'Havuç', amount: 0.5, unit: 'küçük', emoji: '🥕' },
      { name: 'Zeytinyağı', amount: 1, unit: 'yemek kaşığı', emoji: '🫒' },
      { name: 'Su', amount: 200, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Pirinci yıkayıp zeytinyağında kavurun.',
      'Havucu küçük küpler halinde ekleyin.',
      'Su ekleyip kaynatın.',
      'Kısık ateşte 15 dakika pişirin.',
      'Haşlanmış nohutları ekleyip 5 dakika daha pişirin.',
    ],
    nutrients: [
      { name: 'Protein', value: 7, unit: 'g' },
      { name: 'Demir', value: 2.5, unit: 'mg' },
      { name: 'Karbonhidrat', value: 25, unit: 'g' },
    ],
    tip: 'Nohutları bebeğiniz çiğneyemiyorsa hafifçe ezin.',
    createdAt: hoursAgo(96),
  },
  {
    id: '66',
    title: 'Bebek Kurabiyesi',
    description: 'Şekersiz, sağlıklı atıştırmalık kurabiye.',
    emoji: '🍪',
    ageGroup: '12m+',
    prepTime: 30,
    calories: 45,
    servings: 12,
    difficulty: 'medium',
    rating: { average: 4.9, count: 60 },
    likes: 350, views: 2500, comments: 40,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat', 'egg'],
    tags: ['Atıştırmalık', 'Şekersiz', 'Fırın'],
    ingredients: [
      { name: 'Yulaf unu', amount: 1, unit: 'su bardağı', emoji: '🌾', isAllergen: true },
      { name: 'Muz', amount: 1, unit: 'olgun', emoji: '🍌' },
      { name: 'Yumurta', amount: 1, unit: 'adet', emoji: '🥚', isAllergen: true },
      { name: 'Hindistancevizi yağı', amount: 1, unit: 'yemek kaşığı', emoji: '🥥' },
    ],
    steps: [
      'Fırını 170°C\'ye ısıtın.',
      'Muzu çatalla iyice ezin.',
      'Tüm malzemeleri karıştırın.',
      'Kaşıkla yağlı kağıt üzerine yuvarlak şekiller verin.',
      '15-18 dakika altın rengi olana kadar pişirin.',
    ],
    nutrients: [
      { name: 'Karbonhidrat', value: 8, unit: 'g' },
      { name: 'Protein', value: 2, unit: 'g' },
      { name: 'Lif', value: 1, unit: 'g' },
    ],
    tip: 'Hava geçirmez kapta 5 gün saklanabilir. Dondurucuda 1 ay dayanır.',
    createdAt: hoursAgo(97),
  },
  {
    id: '67',
    title: 'Sebzeli Fırın Patates',
    description: 'Renkli sebzelerle doldurulmuş fırın patates.',
    emoji: '🥔',
    ageGroup: '12m+',
    prepTime: 40,
    calories: 170,
    servings: 1,
    difficulty: 'medium',
    rating: { average: 4.6, count: 32 },
    likes: 175, views: 1000, comments: 18,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['milk'],
    tags: ['Sebze', 'Fırın', 'Tam Öğün'],
    ingredients: [
      { name: 'Patates', amount: 1, unit: 'orta boy', emoji: '🥔' },
      { name: 'Brokoli', amount: 2, unit: 'çiçek', emoji: '🥦' },
      { name: 'Havuç', amount: 0.5, unit: 'küçük', emoji: '🥕' },
      { name: 'Lor peyniri', amount: 1, unit: 'yemek kaşığı', emoji: '🧀', isAllergen: true },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Patatesi fırında 200°C\'de 30 dakika pişirin.',
      'Brokoli ve havucu buharda pişirip küçük doğrayın.',
      'Patatesi ortadan ikiye bölüp içini çatalla kabartın.',
      'Sebzeleri ve lor peynirini ekleyip karıştırın.',
      '5 dakika daha fırında gratine edin.',
    ],
    nutrients: [
      { name: 'Karbonhidrat', value: 25, unit: 'g' },
      { name: 'Protein', value: 5, unit: 'g' },
      { name: 'C Vitamini', value: 40, unit: 'mg' },
    ],
    tip: 'Tüm aile için yapıp birlikte yiyebileceğiniz pratik bir tarif.',
    createdAt: hoursAgo(98),
  },
  {
    id: '68',
    title: 'Ev Yapımı Nugget',
    description: 'Hazır nugget\'a sağlıklı alternatif, fırında pişirilir.',
    emoji: '🐔',
    ageGroup: '12m+',
    prepTime: 30,
    calories: 140,
    servings: 8,
    difficulty: 'medium',
    rating: { average: 4.9, count: 55 },
    likes: 320, views: 2200, comments: 35,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat', 'egg'],
    tags: ['Tavuk', 'Fırın', 'Parmak Yiyecek'],
    ingredients: [
      { name: 'Tavuk göğsü', amount: 150, unit: 'gram', emoji: '🐔' },
      { name: 'Galeta unu', amount: 3, unit: 'yemek kaşığı', emoji: '🍞', isAllergen: true },
      { name: 'Yumurta', amount: 1, unit: 'adet', emoji: '🥚', isAllergen: true },
      { name: 'Zeytinyağı', amount: 1, unit: 'yemek kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Fırını 190°C\'ye ısıtın.',
      'Tavuğu şeritler halinde kesin.',
      'Yumurtayı çırpıp tavukları geçirin.',
      'Galeta ununa bulayın.',
      'Yağlanmış tepsiye dizin, 20 dakika pişirin.',
      'Yarısında çevirip altın rengi olana kadar pişirin.',
    ],
    nutrients: [
      { name: 'Protein', value: 18, unit: 'g' },
      { name: 'Karbonhidrat', value: 10, unit: 'g' },
      { name: 'B12 Vitamini', value: 0.5, unit: 'mcg' },
    ],
    tip: 'Fazlasını dondurucuda saklayıp gerektiğinde fırında ısıtabilirsiniz.',
    createdAt: hoursAgo(99),
  },
  {
    id: '69',
    title: 'Mercimek Köftesi',
    description: 'Geleneksel Türk mutfağından bitkisel protein köftesi.',
    emoji: '🟠',
    ageGroup: '12m+',
    prepTime: 25,
    calories: 100,
    servings: 8,
    difficulty: 'medium',
    rating: { average: 4.7, count: 40 },
    likes: 220, views: 1300, comments: 24,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat'],
    tags: ['Bakliyat', 'Geleneksel', 'Bitkisel'],
    ingredients: [
      { name: 'Kırmızı Mercimek', amount: 0.5, unit: 'su bardağı', emoji: '🟠' },
      { name: 'İnce Bulgur', amount: 0.5, unit: 'su bardağı', emoji: '🌾', isAllergen: true },
      { name: 'Soğan', amount: 0.5, unit: 'adet', emoji: '🧅' },
      { name: 'Maydanoz', amount: 2, unit: 'dal', emoji: '🌿' },
      { name: 'Zeytinyağı', amount: 1, unit: 'yemek kaşığı', emoji: '🫒' },
      { name: 'Limon', amount: 0.5, unit: 'adet', emoji: '🍋' },
    ],
    steps: [
      'Mercimeği yıkayıp 1.5 su bardağı su ile haşlayın.',
      'Piştikten sonra ateşten alıp bulguru ekleyin, kapağını kapatıp 15 dakika bekletin.',
      'Soğanı zeytinyağında kavurun, karışıma ekleyin.',
      'Doğranmış maydanoz ve limon suyunu ekleyin.',
      'Yoğurup minik köfteler şekillendirin.',
    ],
    nutrients: [
      { name: 'Protein', value: 6, unit: 'g' },
      { name: 'Demir', value: 2.5, unit: 'mg' },
      { name: 'Lif', value: 4, unit: 'g' },
    ],
    tip: 'Tuzsuz yapın, limon suyu doğal tat verir. Vejetaryen aileler için mükemmel protein kaynağı.',
    createdAt: hoursAgo(100),
  },
  {
    id: '70',
    title: 'Domates Soslu Köfte',
    description: 'Ev yapımı domates sosuyla yumuşak dana köftesi.',
    emoji: '🧆',
    ageGroup: '12m+',
    prepTime: 35,
    calories: 175,
    servings: 8,
    difficulty: 'medium',
    rating: { average: 4.8, count: 42 },
    likes: 235, views: 1400, comments: 26,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Etli', 'Köfte', 'Domates'],
    ingredients: [
      { name: 'Dana kıyma', amount: 100, unit: 'gram', emoji: '🥩' },
      { name: 'Domates', amount: 2, unit: 'adet', emoji: '🍅' },
      { name: 'Soğan', amount: 0.25, unit: 'adet (rendelenmiş)', emoji: '🧅' },
      { name: 'Maydanoz', amount: 1, unit: 'dal', emoji: '🌿' },
      { name: 'Zeytinyağı', amount: 1, unit: 'yemek kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Kıymayı rendelenmiş soğan ve doğranmış maydanozla yoğurun.',
      'Minik köfteler şekillendirin.',
      'Domatesleri rendeleyin, zeytinyağında kavurun.',
      'Köfteleri sosu tencereye dizin.',
      'Kısık ateşte 20-25 dakika pişirin.',
    ],
    nutrients: [
      { name: 'Protein', value: 14, unit: 'g' },
      { name: 'Demir', value: 3, unit: 'mg' },
      { name: 'C Vitamini', value: 15, unit: 'mg' },
    ],
    tip: 'Yanına pirinç pilavı veya makarna ile tam öğün yapabilirsiniz.',
    createdAt: hoursAgo(101),
  },
  {
    id: '71',
    title: 'Peynirli Omlet',
    description: 'Kahvaltının vazgeçilmezi, protein dolu yumuşak omlet.',
    emoji: '🍳',
    ageGroup: '12m+',
    prepTime: 10,
    calories: 130,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.6, count: 48 },
    likes: 260, views: 1600, comments: 28,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['egg', 'milk'],
    tags: ['Kahvaltı', 'Yumurta', 'Kolay'],
    ingredients: [
      { name: 'Yumurta', amount: 1, unit: 'adet', emoji: '🥚', isAllergen: true },
      { name: 'Lor peyniri', amount: 1, unit: 'yemek kaşığı', emoji: '🧀', isAllergen: true },
      { name: 'Domates', amount: 0.25, unit: 'adet', emoji: '🍅' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Yumurtayı çırpın.',
      'Domatesi minik küpler halinde doğrayın.',
      'Tavada zeytinyağını ısıtıp yumurtayı dökün.',
      'Peynir ve domatesi üzerine dağıtın.',
      'Kısık ateşte pişirip katlayın.',
    ],
    nutrients: [
      { name: 'Protein', value: 9, unit: 'g' },
      { name: 'Kalsiyum', value: 60, unit: 'mg' },
      { name: 'D Vitamini', value: 1.5, unit: 'mcg' },
    ],
    tip: 'İçine ıspanak veya maydanoz ekleyerek daha besleyici yapabilirsiniz.',
    createdAt: hoursAgo(102),
  },
  {
    id: '72',
    title: 'Karışık Sebze Kızartması',
    description: 'Fırında hazırlanan sağlıklı sebze kızartması.',
    emoji: '🥗',
    ageGroup: '12m+',
    prepTime: 35,
    calories: 100,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.5, count: 28 },
    likes: 140, views: 800, comments: 12,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Sebze', 'Fırın', 'Sağlıklı'],
    ingredients: [
      { name: 'Kabak', amount: 0.5, unit: 'adet', emoji: '🎃' },
      { name: 'Patlıcan', amount: 0.5, unit: 'küçük', emoji: '🍆' },
      { name: 'Kırmızı biber', amount: 0.5, unit: 'adet', emoji: '🌶️' },
      { name: 'Patates', amount: 1, unit: 'küçük', emoji: '🥔' },
      { name: 'Zeytinyağı', amount: 1, unit: 'yemek kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Fırını 190°C\'ye ısıtın.',
      'Tüm sebzeleri küçük küpler halinde doğrayın.',
      'Zeytinyağı ile harmanlayın.',
      'Fırın tepsisine yayın.',
      '25-30 dakika karıştırarak pişirin.',
    ],
    nutrients: [
      { name: 'Lif', value: 4, unit: 'g' },
      { name: 'C Vitamini', value: 35, unit: 'mg' },
      { name: 'A Vitamini', value: 200, unit: 'mcg' },
    ],
    tip: 'Yanına yoğurt eşliğinde servis edin.',
    createdAt: hoursAgo(103),
  },
  {
    id: '73',
    title: 'Kıymalı Börek Ruloları',
    description: 'Fırında pişen, pratik mini börek ruloları.',
    emoji: '🥟',
    ageGroup: '12m+',
    prepTime: 35,
    calories: 160,
    servings: 8,
    difficulty: 'medium',
    rating: { average: 4.7, count: 35 },
    likes: 190, views: 1100, comments: 20,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat', 'egg'],
    tags: ['Hamur İşi', 'Etli', 'Fırın'],
    ingredients: [
      { name: 'Yufka', amount: 1, unit: 'adet', emoji: '📜', isAllergen: true },
      { name: 'Dana kıyma', amount: 100, unit: 'gram', emoji: '🥩' },
      { name: 'Soğan', amount: 0.5, unit: 'adet', emoji: '🧅' },
      { name: 'Yumurta sarısı', amount: 1, unit: 'adet', emoji: '🥚', isAllergen: true },
      { name: 'Zeytinyağı', amount: 1, unit: 'yemek kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Kıymayı soğanla kavurup soğumaya bırakın.',
      'Yufkayı üçgen dilimler halinde kesin.',
      'Her dilimin geniş ucuna iç malzeme koyun.',
      'Rulo yapıp tepsiye dizin.',
      'Yumurta sarısı sürüp 180°C fırında 20 dakika pişirin.',
    ],
    nutrients: [
      { name: 'Protein', value: 10, unit: 'g' },
      { name: 'Karbonhidrat', value: 15, unit: 'g' },
      { name: 'Demir', value: 2, unit: 'mg' },
    ],
    tip: 'İç harcını peynirli de yapabilirsiniz. Dondurucuda 2 ay saklanır.',
    createdAt: hoursAgo(104),
  },
  {
    id: '74',
    title: 'Kereviz Yemeği',
    description: 'Zeytinyağlı, hafif ve vitamin dolu kereviz.',
    emoji: '🥬',
    ageGroup: '12m+',
    prepTime: 40,
    calories: 95,
    servings: 1,
    difficulty: 'medium',
    rating: { average: 4.4, count: 22 },
    likes: 110, views: 650, comments: 10,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Sebze', 'Zeytinyağlı', 'Geleneksel'],
    ingredients: [
      { name: 'Kereviz', amount: 1, unit: 'küçük', emoji: '🥬' },
      { name: 'Havuç', amount: 1, unit: 'küçük', emoji: '🥕' },
      { name: 'Patates', amount: 1, unit: 'küçük', emoji: '🥔' },
      { name: 'Bezelye', amount: 2, unit: 'yemek kaşığı', emoji: '🟢' },
      { name: 'Zeytinyağı', amount: 1, unit: 'yemek kaşığı', emoji: '🫒' },
      { name: 'Limon', amount: 0.5, unit: 'adet', emoji: '🍋' },
    ],
    steps: [
      'Kerevizi soyup küçük küpler halinde doğrayın.',
      'Havuç ve patatesi de küçük doğrayın.',
      'Zeytinyağında sebzeleri hafif kavurun.',
      'Su ekleyip kısık ateşte 30 dakika pişirin.',
      'Limon suyu sıkıp servis edin.',
    ],
    nutrients: [
      { name: 'Lif', value: 3.5, unit: 'g' },
      { name: 'C Vitamini', value: 20, unit: 'mg' },
      { name: 'Potasyum', value: 280, unit: 'mg' },
    ],
    tip: 'Kereviz limon ile birlikte daha lezzetli olur ve demir emilimini artırır.',
    createdAt: hoursAgo(105),
  },
  {
    id: '75',
    title: 'Tavuklu Fırın Makarna',
    description: 'Kremalı peynirli sos ile fırında pişen makarna.',
    emoji: '🍝',
    ageGroup: '12m+',
    prepTime: 35,
    calories: 200,
    servings: 2,
    difficulty: 'medium',
    rating: { average: 4.8, count: 50 },
    likes: 280, views: 1800, comments: 30,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat', 'milk'],
    tags: ['Makarna', 'Tavuk', 'Fırın'],
    ingredients: [
      { name: 'Bebek makarnası', amount: 50, unit: 'gram', emoji: '🍝', isAllergen: true },
      { name: 'Tavuk göğsü', amount: 50, unit: 'gram', emoji: '🐔' },
      { name: 'Lor peyniri', amount: 1, unit: 'yemek kaşığı', emoji: '🧀', isAllergen: true },
      { name: 'Domates', amount: 1, unit: 'küçük', emoji: '🍅' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Makarnayı haşlayıp süzün.',
      'Tavuğu küçük parçalar halinde pişirin.',
      'Domatesi rendeleyin, zeytinyağında kavurun.',
      'Tümünü karıştırıp üzerine lor peyniri serpin.',
      '180°C fırında 10 dakika gratine edin.',
    ],
    nutrients: [
      { name: 'Protein', value: 15, unit: 'g' },
      { name: 'Karbonhidrat', value: 25, unit: 'g' },
      { name: 'Kalsiyum', value: 80, unit: 'mg' },
    ],
    tip: 'Makarnayı biraz az haşlayın, fırında pişerken yumuşar.',
    createdAt: hoursAgo(106),
  },
  {
    id: '76',
    title: 'Zeytinyağlı Enginar',
    description: 'Bezelye ve havuçlu geleneksel enginar yemeği.',
    emoji: '🌿',
    ageGroup: '12m+',
    prepTime: 45,
    calories: 110,
    servings: 2,
    difficulty: 'medium',
    rating: { average: 4.5, count: 25 },
    likes: 130, views: 750, comments: 14,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Sebze', 'Zeytinyağlı', 'Geleneksel'],
    ingredients: [
      { name: 'Enginar', amount: 2, unit: 'adet (konserve)', emoji: '🌿' },
      { name: 'Bezelye', amount: 3, unit: 'yemek kaşığı', emoji: '🟢' },
      { name: 'Havuç', amount: 1, unit: 'küçük', emoji: '🥕' },
      { name: 'Patates', amount: 1, unit: 'küçük', emoji: '🥔' },
      { name: 'Zeytinyağı', amount: 1, unit: 'yemek kaşığı', emoji: '🫒' },
      { name: 'Limon suyu', amount: 1, unit: 'yemek kaşığı', emoji: '🍋' },
    ],
    steps: [
      'Enginarları temizleyip limonlu suda bekletin.',
      'Havuç ve patatesi küçük küpler halinde doğrayın.',
      'Zeytinyağında sebzeleri kavurun.',
      'Enginarları ekleyip su ilave edin.',
      'Kısık ateşte 30 dakika pişirin, limon sıkıp servis edin.',
    ],
    nutrients: [
      { name: 'Lif', value: 5, unit: 'g' },
      { name: 'C Vitamini', value: 15, unit: 'mg' },
      { name: 'Potasyum', value: 300, unit: 'mg' },
    ],
    tip: 'Konserve enginar kullanmak zaman kazandırır.',
    createdAt: hoursAgo(107),
  },
  {
    id: '77',
    title: 'Pirinç Sütlacı',
    description: 'Şekersiz, sütlü tatlı, bebek dostu.',
    emoji: '🍚',
    ageGroup: '12m+',
    prepTime: 30,
    calories: 130,
    servings: 2,
    difficulty: 'easy',
    rating: { average: 4.7, count: 38 },
    likes: 200, views: 1200, comments: 22,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['milk'],
    tags: ['Tatlı', 'Süt', 'Geleneksel'],
    ingredients: [
      { name: 'Pirinç', amount: 2, unit: 'yemek kaşığı', emoji: '🍚' },
      { name: 'Süt', amount: 200, unit: 'ml', emoji: '🥛', isAllergen: true },
      { name: 'Hurma', amount: 1, unit: 'adet (püresi)', emoji: '🌴' },
    ],
    steps: [
      'Pirinci yıkayıp az suda yumuşatın.',
      'Sütü ekleyip kısık ateşte karıştırarak pişirin.',
      'Hurma püresi ekleyip 5 dakika daha pişirin.',
      'Koyulaşınca ateşten alıp soğumaya bırakın.',
    ],
    nutrients: [
      { name: 'Kalsiyum', value: 180, unit: 'mg' },
      { name: 'Karbonhidrat', value: 20, unit: 'g' },
      { name: 'Protein', value: 5, unit: 'g' },
    ],
    tip: 'Hurma doğal tatlandırıcıdır, şeker eklemeye gerek yoktur.',
    createdAt: hoursAgo(108),
  },
  {
    id: '78',
    title: 'Sebzeli Çörek',
    description: 'İçinde havuç ve kabak gizlenmiş yumuşak çörekler.',
    emoji: '🥐',
    ageGroup: '12m+',
    prepTime: 40,
    calories: 120,
    servings: 6,
    difficulty: 'medium',
    rating: { average: 4.6, count: 30 },
    likes: 160, views: 950, comments: 16,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat', 'egg', 'milk'],
    tags: ['Hamur İşi', 'Sebze', 'Fırın'],
    ingredients: [
      { name: 'Un', amount: 1, unit: 'su bardağı', emoji: '🌾', isAllergen: true },
      { name: 'Yoğurt', amount: 3, unit: 'yemek kaşığı', emoji: '🥛', isAllergen: true },
      { name: 'Yumurta', amount: 1, unit: 'adet', emoji: '🥚', isAllergen: true },
      { name: 'Havuç', amount: 1, unit: 'rendelenmiş', emoji: '🥕' },
      { name: 'Kabak', amount: 0.5, unit: 'rendelenmiş', emoji: '🎃' },
      { name: 'Zeytinyağı', amount: 2, unit: 'yemek kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Yoğurt, yumurta ve zeytinyağını karıştırın.',
      'Rendelenmiş sebzeleri ekleyin.',
      'Unu azar azar ilave edip yumuşak hamur yapın.',
      'Minik toplar şekillendirip tepsiye dizin.',
      '180°C fırında 20-25 dakika pişirin.',
    ],
    nutrients: [
      { name: 'A Vitamini', value: 300, unit: 'mcg' },
      { name: 'Protein', value: 4, unit: 'g' },
      { name: 'Karbonhidrat', value: 15, unit: 'g' },
    ],
    tip: 'Sebze yemeyen bebekler için gizli sebze tarifi.',
    createdAt: hoursAgo(109),
  },
  {
    id: '93',
    title: 'Fırında Patlıcan Musakka',
    description: 'Kıymalı patlıcan musakka, bebek porsiyonunda.',
    emoji: '🍆',
    ageGroup: '12m+',
    prepTime: 45,
    calories: 180,
    servings: 2,
    difficulty: 'medium',
    rating: { average: 4.7, count: 35 },
    likes: 190, views: 1100, comments: 20,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Etli', 'Sebze', 'Geleneksel'],
    ingredients: [
      { name: 'Patlıcan', amount: 1, unit: 'küçük', emoji: '🍆' },
      { name: 'Dana kıyma', amount: 80, unit: 'gram', emoji: '🥩' },
      { name: 'Domates', amount: 1, unit: 'adet', emoji: '🍅' },
      { name: 'Biber', amount: 1, unit: 'küçük', emoji: '🌶️' },
      { name: 'Zeytinyağı', amount: 1, unit: 'yemek kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Patlıcanı küp küp doğrayıp zeytinyağında soteleyin.',
      'Kıymayı ayrı tavada kavurun.',
      'Domatesi rendeleyin, biber ve soğanla kavurun.',
      'Fırın kabına alt alta dizin.',
      '180°C fırında 20 dakika pişirin.',
    ],
    nutrients: [
      { name: 'Protein', value: 12, unit: 'g' },
      { name: 'Demir', value: 2.5, unit: 'mg' },
      { name: 'Lif', value: 3, unit: 'g' },
    ],
    tip: 'Patlıcanı tuzlayıp bekletmeyin, doğrudan pişirin.',
    createdAt: hoursAgo(124),
  },
  {
    id: '94',
    title: 'Peynirli Ispanak Böreği',
    description: 'Demir ve kalsiyum deposu, yumuşak mini börekler.',
    emoji: '🥬',
    ageGroup: '12m+',
    prepTime: 35,
    calories: 145,
    servings: 6,
    difficulty: 'medium',
    rating: { average: 4.8, count: 42 },
    likes: 230, views: 1400, comments: 25,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat', 'milk', 'egg'],
    tags: ['Hamur İşi', 'Sebze', 'Ispanak'],
    ingredients: [
      { name: 'Yufka', amount: 1, unit: 'adet', emoji: '📜', isAllergen: true },
      { name: 'Ispanak', amount: 1, unit: 'avuç', emoji: '🥬' },
      { name: 'Lor peyniri', amount: 3, unit: 'yemek kaşığı', emoji: '🧀', isAllergen: true },
      { name: 'Yumurta', amount: 1, unit: 'adet', emoji: '🥚', isAllergen: true },
      { name: 'Zeytinyağı', amount: 1, unit: 'yemek kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Ispanağı yıkayıp haşlayın, suyunu sıkın.',
      'İnce kıyıp lor peyniriyle karıştırın.',
      'Yufkayı şeritler halinde kesin.',
      'İç malzeme koyup üçgen börekler yapın.',
      'Yumurta sürüp 180°C fırında 20 dakika pişirin.',
    ],
    nutrients: [
      { name: 'Demir', value: 3, unit: 'mg' },
      { name: 'Kalsiyum', value: 150, unit: 'mg' },
      { name: 'Protein', value: 8, unit: 'g' },
    ],
    tip: 'Dondurucuda çiğ halde saklayıp gerektiğinde pişirebilirsiniz.',
    createdAt: hoursAgo(125),
  },
  {
    id: '95',
    title: 'Tavuklu Noodle',
    description: 'Asya esintili, sebzeli tavuklu erişte.',
    emoji: '🍜',
    ageGroup: '12m+',
    prepTime: 20,
    calories: 165,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.6, count: 30 },
    likes: 170, views: 1000, comments: 16,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat'],
    tags: ['Tavuk', 'Erişte', 'Sebze'],
    ingredients: [
      { name: 'Erişte', amount: 40, unit: 'gram', emoji: '🍜', isAllergen: true },
      { name: 'Tavuk göğsü', amount: 40, unit: 'gram', emoji: '🐔' },
      { name: 'Havuç', amount: 0.5, unit: 'küçük', emoji: '🥕' },
      { name: 'Kabak', amount: 0.5, unit: 'küçük', emoji: '🎃' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Erişteyı haşlayıp süzün.',
      'Tavuğu küçük şeritler halinde pişirin.',
      'Sebzeleri ince doğrayıp soteleyin.',
      'Tümünü birleştirip zeytinyağı ile karıştırın.',
    ],
    nutrients: [
      { name: 'Protein', value: 12, unit: 'g' },
      { name: 'Karbonhidrat', value: 20, unit: 'g' },
      { name: 'A Vitamini', value: 200, unit: 'mcg' },
    ],
    tip: 'Erişteyı çok yumuşak haşlayın, küçük parçalara kırın.',
    createdAt: hoursAgo(126),
  },
  {
    id: '96',
    title: 'Karnabahar Graten',
    description: 'Peynirli ve kremalı, sebze sevdiren tarif.',
    emoji: '🥦',
    ageGroup: '12m+',
    prepTime: 30,
    calories: 140,
    servings: 2,
    difficulty: 'medium',
    rating: { average: 4.7, count: 33 },
    likes: 180, views: 1050, comments: 18,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['milk'],
    tags: ['Sebze', 'Peynir', 'Fırın'],
    ingredients: [
      { name: 'Karnabahar', amount: 150, unit: 'gram', emoji: '🥦' },
      { name: 'Lor peyniri', amount: 2, unit: 'yemek kaşığı', emoji: '🧀', isAllergen: true },
      { name: 'Süt', amount: 50, unit: 'ml', emoji: '🥛', isAllergen: true },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Karnabaharı çiçeklerine ayırıp buharda 10 dakika pişirin.',
      'Fırın kabına dizin.',
      'Süt ve lor peynirini karıştırıp üzerine dökün.',
      '180°C fırında 15 dakika gratine edin.',
    ],
    nutrients: [
      { name: 'C Vitamini', value: 50, unit: 'mg' },
      { name: 'Kalsiyum', value: 100, unit: 'mg' },
      { name: 'Lif', value: 3, unit: 'g' },
    ],
    tip: 'Karnabahar C vitamini şampiyonudur.',
    createdAt: hoursAgo(127),
  },
  {
    id: '97',
    title: 'Ev Yapımı Pizza',
    description: 'Sağlıklı malzemelerle bebek dostu mini pizza.',
    emoji: '🍕',
    ageGroup: '12m+',
    prepTime: 40,
    calories: 190,
    servings: 4,
    difficulty: 'medium',
    rating: { average: 4.9, count: 55 },
    likes: 320, views: 2200, comments: 38,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['wheat', 'milk'],
    tags: ['Hamur İşi', 'Eğlenceli', 'Sebze'],
    ingredients: [
      { name: 'Un', amount: 1, unit: 'su bardağı', emoji: '🌾', isAllergen: true },
      { name: 'Yoğurt', amount: 3, unit: 'yemek kaşığı', emoji: '🥛', isAllergen: true },
      { name: 'Domates sosu', amount: 2, unit: 'yemek kaşığı', emoji: '🍅' },
      { name: 'Lor peyniri', amount: 2, unit: 'yemek kaşığı', emoji: '🧀', isAllergen: true },
      { name: 'Kabak', amount: 0.5, unit: 'ince dilim', emoji: '🎃' },
      { name: 'Zeytinyağı', amount: 1, unit: 'yemek kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Un, yoğurt ve zeytinyağıyla yumuşak hamur yapın.',
      'Hamuru mini daireler halinde açın.',
      'Domates sosunu sürün.',
      'Sebze ve peyniri dağıtın.',
      '200°C fırında 15-18 dakika pişirin.',
    ],
    nutrients: [
      { name: 'Karbonhidrat', value: 22, unit: 'g' },
      { name: 'Protein', value: 7, unit: 'g' },
      { name: 'Kalsiyum', value: 80, unit: 'mg' },
    ],
    tip: 'BLW (Baby Led Weaning) için mükemmel parmak yiyecek.',
    createdAt: hoursAgo(128),
  },
  {
    id: '98',
    title: 'Balıklı Patates Kroket',
    description: 'Omega-3 zengin, fırında pişen balık kroketleri.',
    emoji: '🐟',
    ageGroup: '12m+',
    prepTime: 35,
    calories: 155,
    servings: 6,
    difficulty: 'medium',
    rating: { average: 4.6, count: 28 },
    likes: 150, views: 900, comments: 14,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: ['fish', 'egg'],
    tags: ['Balık', 'Fırın', 'Parmak Yiyecek'],
    ingredients: [
      { name: 'Somon fileto', amount: 80, unit: 'gram', emoji: '🐟', isAllergen: true },
      { name: 'Patates', amount: 1, unit: 'orta boy', emoji: '🥔' },
      { name: 'Yumurta', amount: 1, unit: 'adet', emoji: '🥚', isAllergen: true },
      { name: 'Dereotu', amount: 1, unit: 'dal', emoji: '🌿' },
      { name: 'Zeytinyağı', amount: 1, unit: 'yemek kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Patatesi haşlayıp püre yapın.',
      'Somonu buharda pişirip didikleyin.',
      'Patates, balık ve doğranmış dereotunu karıştırın.',
      'Minik kroketler şekillendirin.',
      'Yumurta sürüp 190°C fırında 20 dakika pişirin.',
    ],
    nutrients: [
      { name: 'Omega-3', value: 500, unit: 'mg' },
      { name: 'Protein', value: 14, unit: 'g' },
      { name: 'D Vitamini', value: 3, unit: 'mcg' },
    ],
    tip: 'Somon yerine levrek veya çipura da kullanılabilir.',
    createdAt: hoursAgo(129),
  },
  {
    id: '99',
    title: 'Lahana Sarması',
    description: 'Geleneksel lahana sarması, bebek porsiyonunda.',
    emoji: '🥬',
    ageGroup: '12m+',
    prepTime: 50,
    calories: 140,
    servings: 6,
    difficulty: 'hard',
    rating: { average: 4.5, count: 25 },
    likes: 130, views: 800, comments: 12,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Geleneksel', 'Etli', 'Sebze'],
    ingredients: [
      { name: 'Lahana yaprağı', amount: 6, unit: 'adet', emoji: '🥬' },
      { name: 'Dana kıyma', amount: 80, unit: 'gram', emoji: '🥩' },
      { name: 'Pirinç', amount: 2, unit: 'yemek kaşığı', emoji: '🍚' },
      { name: 'Soğan', amount: 0.5, unit: 'adet', emoji: '🧅' },
      { name: 'Domates', amount: 1, unit: 'adet', emoji: '🍅' },
      { name: 'Zeytinyağı', amount: 1, unit: 'yemek kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Lahana yapraklarını haşlayıp yumuşatın.',
      'Kıyma, pirinç, rendelenmiş soğan ve baharatları karıştırın.',
      'Her yaprağa iç malzeme koyup sarın.',
      'Tencereye dizin, rendelenmiş domates ve su ekleyin.',
      'Kısık ateşte 40 dakika pişirin.',
    ],
    nutrients: [
      { name: 'Protein', value: 10, unit: 'g' },
      { name: 'Demir', value: 2, unit: 'mg' },
      { name: 'C Vitamini', value: 20, unit: 'mg' },
    ],
    tip: 'Aile sofrasındakinden ayırıp tuzsuz pişirin.',
    createdAt: hoursAgo(130),
  },
  {
    id: '100',
    title: 'Meyve Salatası',
    description: 'Renkli mevsim meyveleri ile vitamin dolu salata.',
    emoji: '🍇',
    ageGroup: '12m+',
    prepTime: 10,
    calories: 80,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.8, count: 50 },
    likes: 280, views: 1800, comments: 30,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Meyve', 'Vitamin', 'Kolay'],
    ingredients: [
      { name: 'Muz', amount: 0.5, unit: 'adet', emoji: '🍌' },
      { name: 'Çilek', amount: 3, unit: 'adet', emoji: '🍓' },
      { name: 'Kivi', amount: 0.5, unit: 'adet', emoji: '🥝' },
      { name: 'Üzüm', amount: 5, unit: 'tane (ikiye bölünmüş)', emoji: '🍇' },
    ],
    steps: [
      'Tüm meyveleri küçük parçalara doğrayın.',
      'Üzümleri mutlaka ikiye veya dörde bölün (boğulma riski).',
      'Hepsini karıştırın.',
      'Hemen servis edin.',
    ],
    nutrients: [
      { name: 'C Vitamini', value: 40, unit: 'mg' },
      { name: 'Potasyum', value: 250, unit: 'mg' },
      { name: 'Lif', value: 3, unit: 'g' },
    ],
    tip: 'Üzüm ve kiraz gibi yuvarlak meyveleri mutlaka kesin, boğulma tehlikesi var.',
    createdAt: hoursAgo(131),
  },
  {
    id: '101',
    title: 'Zeytinyağlı Barbunya',
    description: 'Geleneksel zeytinyağlı barbunya, bebekler için tuzsuz.',
    emoji: '🫘',
    ageGroup: '12m+',
    prepTime: 60,
    calories: 130,
    servings: 3,
    difficulty: 'medium',
    rating: { average: 4.5, count: 22 },
    likes: 120, views: 700, comments: 10,
    isLiked: false, isAIGenerated: false,
    source: 'official', authorName: 'Kaşık Ekibi', authorVerified: true,
    allergens: [],
    tags: ['Bakliyat', 'Zeytinyağlı', 'Geleneksel'],
    ingredients: [
      { name: 'Barbunya', amount: 0.5, unit: 'su bardağı', emoji: '🫘' },
      { name: 'Domates', amount: 1, unit: 'adet', emoji: '🍅' },
      { name: 'Soğan', amount: 0.5, unit: 'adet', emoji: '🧅' },
      { name: 'Havuç', amount: 1, unit: 'küçük', emoji: '🥕' },
      { name: 'Patates', amount: 1, unit: 'küçük', emoji: '🥔' },
      { name: 'Zeytinyağı', amount: 1, unit: 'yemek kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Barbunyayı önceden 8 saat suda bekletin.',
      'Süzüp temiz suyla haşlamaya başlayın.',
      'Yarı piştikten sonra doğranmış sebzeleri ekleyin.',
      'Zeytinyağı ilave edip kısık ateşte pişirin.',
      'Yumuşayınca servis edin, gerekirse çatalla ezin.',
    ],
    nutrients: [
      { name: 'Protein', value: 8, unit: 'g' },
      { name: 'Demir', value: 3, unit: 'mg' },
      { name: 'Lif', value: 6, unit: 'g' },
    ],
    tip: 'Bakliyat gaz yapabilir, az miktarla başlayın.',
    createdAt: hoursAgo(132),
  },
];
