/**
 * Tarif Görselleri — 344 adet local görsel
 * Grid resimlerden kesilmiş 200x200 JPG
 */

const RECIPE_IMAGE_MAP: Record<string, any> = {
  'armut___avokado': require('../assets/recipes/armut___avokado.jpg'),
  'armut___ceviz': require('../assets/recipes/yumurta_sarisi___armut_puresi.jpg'),
  'armut___elma': require('../assets/recipes/armut___elma.jpg'),
  'armut___yogurt': require('../assets/recipes/yogurt.jpg'),
  'armut_puresi': require('../assets/recipes/armut_puresi.jpg'),
  'avokado___kabak_yogurt': require('../assets/recipes/avokado___kabak_yogurt.jpg'),
  'avokado___labne_yumurta_sarisi_elma_puresi': require('../assets/recipes/elma_puresi.jpg'),
  'avokado___labneli_pure_yumurta_sarisi_ile_omlet_toz_ceviz_tadimi': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'avokado___labneli_pure_yumurta_sarisi_ile_pankek_toz_ceviz_tadimi': require('../assets/recipes/yumurta_sarisi_ile_pankek_toz_ceviz.jpg'),
  'avokado___lor___yumurta___muz': require('../assets/recipes/avokado___lor___yumurta___muz.jpg'),
  'avokado___lor_yumurta_sarisi_armut_puresi': require('../assets/recipes/armut_puresi.jpg'),
  'avokado___lor_yumurta_sarisi_muz_puresi': require('../assets/recipes/elma___avokado_yogurt.jpg'),
  'avokado___patates': require('../assets/recipes/avokado___patates.jpg'),
  'avokado_ezmesi': require('../assets/recipes/avokado_ezmesi.jpg'),
  'avokado_puresi': require('../assets/recipes/avokado_puresi.jpg'),
  'avokado_muz_ezmesi': require('../assets/recipes/muz_ezmesi.jpg'),
  'balkabakli_risotto': require('../assets/recipes/kuzu_kiymali_semizotlu_kabakli_havuclu_mucver.jpg'),
  'balkabakli_krep': require('../assets/recipes/yumurta_sarisi_ile_krep.jpg'),
  'balkabakli_pankek___labne___avokado___muz': require('../assets/recipes/yumurta_sarisi_ile_pankek_toz_ceviz.jpg'),
  'balkabakli_corba___sebzeli_makarna': require('../assets/recipes/havuckabakpirinc_corbasi.jpg'),
  'balkabagi_puresi': require('../assets/recipes/balkabagi_puresi.jpg'),
  'balkabagi_corbasi___sebzeli_makarna': require('../assets/recipes/havuckabakpirinc_corbasi.jpg'),
  'balik___mercimekli_bulgur_pilavi': require('../assets/recipes/mercimek_corbasi.jpg'),
  'balik___sebzeli_bulgur_pilavi': require('../assets/recipes/bulgurlu_yemek.jpg'),
  'balik___sebzeli_eriste': require('../assets/recipes/kuzu_kiyma_ile_sebzeli_eriste.jpg'),
  'balik___sebzeli_makarna': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'balik___tatli_patates_puresi': require('../assets/recipes/patates_puresi.jpg'),
  'balik___tatli_patates_puresi___tam_bugday_ekmegi': require('../assets/recipes/patates_puresi.jpg'),
  'balik___yesil_mercimekli_bulgur_pilavi': require('../assets/recipes/mercimek_corbasi.jpg'),
  'balikli_patates_kroket': require('../assets/recipes/avokado___patates.jpg'),
  'bamya_yemegi___pilav___yogurt': require('../assets/recipes/yogurt.jpg'),
  'bezelye_puresi': require('../assets/recipes/bezelye_puresi.jpg'),
  'bezelye_yemegi_havuclu_patatesli_kiymali_domatesli___yogurt': require('../assets/recipes/yogurt.jpg'),
  'bezelyeli_patates_puresi': require('../assets/recipes/bezelyeli_patates_puresi.jpg'),
  'biber_dolmasi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'biberli_omlet___labne___zeytin___avokado': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'brokoli_puresi': require('../assets/recipes/brokoli_puresi.jpg'),
  'brokoli_corbasi': require('../assets/recipes/havuckabakpirinc_corbasi.jpg'),
  'brokoli_corbasi___tam_bugday_ekmegi': require('../assets/recipes/havuckabakpirinc_corbasi.jpg'),
  'bulgurlu_kofte': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'bulgurlu_kabak_yemegi': require('../assets/recipes/bulgurlu_yemek.jpg'),
  'bulgurlu_kabak_yemegi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'bulgurlu_ispanak_yemegi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'domates_soslu_kofte': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'domates_ve_yumurta_sarisi_ile_menemen_labne_peyniri_tam_bugday_ekmegi_meyve___avokado': require('../assets/recipes/domates_ve_yumurta_sarisi_menemen.jpg'),
  'domates_ve_yumurta_sarisi_ile_menemen_lor_peyniri_tam_bugday_ekmegi_meyve': require('../assets/recipes/domates_ve_yumurta_sarisi_menemen.jpg'),
  'elma___avokado': require('../assets/recipes/elma___avokado.jpg'),
  'elma___avokado_yogurt': require('../assets/recipes/elma___avokado_yogurt.jpg'),
  'elma_puresi': require('../assets/recipes/elma_puresi.jpg'),
  'elmali_pirinc_puresi': require('../assets/recipes/elmali_pirinc_puresi.jpg'),
  'elmali_yulaf_lapasi': require('../assets/recipes/elma___avokado_yogurt.jpg'),
  'elmali_yulafli_haslanmis_labne_peynirli_karisim_yanina_1_adet_yumurta_sarisi': require('../assets/recipes/elma___avokado_yogurt.jpg'),
  'erik_puresi': require('../assets/recipes/erik_puresi.jpg'),
  'erikli_yulaf_puresi': require('../assets/recipes/erikli_yulaf_puresi.jpg'),
  'eriste___yogurt': require('../assets/recipes/yogurt.jpg'),
  'et_patates_haslama___yogurt': require('../assets/recipes/yogurt.jpg'),
  'etli_bruksel_lahanasi___bulgur_pilavi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'etli_nohut___sehriye_pilavi___cacik': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'etli_nohut_yemegi___bulgur_pilavi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'etli_nohut_yemegi___eriste___yogurt': require('../assets/recipes/yogurt.jpg'),
  'etli_nohut_yemegi___sehriye_pilavi___cacik': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'etli_sebzeli_haslama___bulgur_pilavi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'ev_yapimi_nugget': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'ev_yapimi_biskuvi___mevsim_meyvesi': require('../assets/recipes/krep___lor___meyve.jpg'),
  'ev_yapimi_kek___kefir': require('../assets/recipes/yumurta_sarisi_ile_pankek_toz_ceviz.jpg'),
  'ev_yapimi_kek___mevsim_meyvesi': require('../assets/recipes/yumurta_sarisi_ile_pankek_toz_ceviz.jpg'),
  'ev_yapimi_sebzeli_muffin___ayran___kuruyemis': require('../assets/recipes/sebzeli_muffin_kek.jpg'),
  'firin_balik___firin_sebze___yogurt': require('../assets/recipes/yogurt.jpg'),
  'firin_tavuk___sebzeler___yogurt': require('../assets/recipes/yogurt.jpg'),
  'firin_tavuk___sebzeli_eriste': require('../assets/recipes/kuzu_kiyma_ile_sebzeli_eriste.jpg'),
  'firinda_sebze_cubuklari': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'firinda_patatesli_tavuk___yogurt': require('../assets/recipes/yogurt.jpg'),
  'havuc___kabak_puresi': require('../assets/recipes/havuc___kabak_puresi.jpg'),
  'havuc_puresi': require('../assets/recipes/havuc_puresi.jpg'),
  'havuc_puresi___pirinc_tadimlik_yogurt': require('../assets/recipes/havuc_puresi.jpg'),
  'havuc_patates_ve_tadimlik_bezelye_ile_yemek___yogurt': require('../assets/recipes/yogurt.jpg'),
  'havuc_elma_puresi': require('../assets/recipes/elma_puresi.jpg'),
  'havuc_kabak_pirinc_corbasi': require('../assets/recipes/havuckabakpirinc_corbasi.jpg'),
  'havuc_portakal_puresi': require('../assets/recipes/kuzu_kiymali_semizotlu_kabakli_havuclu_mucver.jpg'),
  'havuclu_patatesli_pirincli_ve_kuzu_kiymali_yemek___yogurt': require('../assets/recipes/yogurt.jpg'),
  'haslama_et___sebzeler___yogurt': require('../assets/recipes/yogurt.jpg'),
  'haslama_yumurta___dil_peyniri___pogaca': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'haslama_yumurta___labne___yulafli_muz': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'haslama_yumurta___yulaf_lapasi': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'haslanmis_yumurta___dil_peyniri___avokado': require('../assets/recipes/elma___avokado_yogurt.jpg'),
  'haslanmis_yumurta___dil_peyniri___bebek_biskuvisi': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'haslanmis_yumurta___dil_peyniri___tahin_pekmez': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'haslanmis_yumurta___dil_peyniri___yulafli_lapa': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'haslanmis_yumurta___dil_peyniri___zeytin': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'haslanmis_yumurta___kasar_peyniri___avokado': require('../assets/recipes/elma___avokado_yogurt.jpg'),
  'haslanmis_yumurta___kasar_peynirli_tost': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'haslanmis_yumurta___lor___avokado': require('../assets/recipes/elma___avokado_yogurt.jpg'),
  'haslanmis_yumurta___lor___avokado___yulafli_lapa': require('../assets/recipes/elma___avokado_yogurt.jpg'),
  'haslanmis_yumurta___lor___avokado___zeytin': require('../assets/recipes/elma___avokado_yogurt.jpg'),
  'haslanmis_yumurta___lor___elmali_yulaf': require('../assets/recipes/elma___avokado_yogurt.jpg'),
  'haslanmis_yumurta___lor___yulafli_lapa': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'haslanmis_yumurta___peynir___zeytin': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'haslanmis_yumurta___zeytin___krep': require('../assets/recipes/yumurta_sarisi_ile_krep.jpg'),
  'haslanmis_yumurta___zeytin___pankek': require('../assets/recipes/yumurta_sarisi_ile_pankek_toz_ceviz.jpg'),
  'ispanak_yemegi___eriste___yogurt': require('../assets/recipes/yogurt.jpg'),
  'ispanak_yemegi___makarna___yogurt': require('../assets/recipes/yogurt.jpg'),
  'ispanak_patates_puresi': require('../assets/recipes/patates_puresi.jpg'),
  'ispanakli_krep': require('../assets/recipes/yumurta_sarisi_ile_krep.jpg'),
  'ispanakli_omlet___lor_peyniri___salatalik': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'ispanakli_pankek_veya_muffin': require('../assets/recipes/yumurta_sarisi_ile_pankek_toz_ceviz.jpg'),
  'izgara_balik___mercimekli_bulgur_pilavi': require('../assets/recipes/mercimek_corbasi.jpg'),
  'kabak_puresi': require('../assets/recipes/kabak_puresi.jpg'),
  'kabak_puresi___pirinc_tadimlik_yogurt': require('../assets/recipes/kabak_puresi___pirinc.jpg'),
  'kabak_puresi_yogurt': require('../assets/recipes/yogurt.jpg'),
  'kabak_ve_semizotlu_kiymali_sebze_yemegi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kabak_yemegi_kiymali___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kabak_bezelye_puresi': require('../assets/recipes/bezelye_puresi.jpg'),
  'kabak_elma_puresi': require('../assets/recipes/elma_puresi.jpg'),
  'kabakli_kuzu_kiymali_ve_pirincli_yemek___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kabakli_mucver_sebzeli_kiymali_eriste_yogurt': require('../assets/recipes/yogurt.jpg'),
  'kabakli_ve_sehriyeli_kiymali_corba___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kapya_biberli_omlet___labne___zeytin': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'karnabahar_yemegi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'karisik_sebze_kizartmasi': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'kavurma_et___sebzeli_eriste': require('../assets/recipes/kuzu_kiyma_ile_sebzeli_eriste.jpg'),
  'kayisili_yulaf_lapasi': require('../assets/recipes/kayisili_yulaf_lapasi.jpg'),
  'kasar_peynirli_tost___domates___salatalik': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'kasarli_omlet___yulafli_gun_kurusu': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'kasarli_patatesli_omlet___labne___yulaf': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'kasarli_sebzeli_yulaf_tost___salatalik': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'kefir___kuru_meyveler___kuruyemis': require('../assets/recipes/krep___lor___meyve.jpg'),
  'kefir___mevsim_meyvesi': require('../assets/recipes/krep___lor___meyve.jpg'),
  'kefir___mevsim_meyvesi___kuruyemis': require('../assets/recipes/krep___lor___meyve.jpg'),
  'keci_peynirli_makarna': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'krep___avokado___labne___zeytin': require('../assets/recipes/yumurta_sarisi_ile_krep.jpg'),
  'krep___avokado_labne___zeytin___pekmez': require('../assets/recipes/yumurta_sarisi_ile_krep.jpg'),
  'kuru_meyve___kefir': require('../assets/recipes/krep___lor___meyve.jpg'),
  'kuru_meyveler___karadut_suyu___kuruyemis': require('../assets/recipes/krep___lor___meyve.jpg'),
  'kurufasulye___pilav___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kurufasulye___pirinc_pilavi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kuzu_etli_sebze_puresi': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'kuzu_kofte___eriste': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'kuzu_kiyma_ile_sebzeli_kofte_sebzeli_eriste_yogurt': require('../assets/recipes/yogurt.jpg'),
  'kuzu_kiymali_semizotlu_kabakli_havuclu_mucver___yogurt': require('../assets/recipes/kuzu_kiymali_semizotlu_kabakli_havuclu_mucver.jpg'),
  'kofte___sebzeli_eriste___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kofte___sebzeli_makarna': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'kirmizi_mercimekli_corba___bulgur_pilavi': require('../assets/recipes/havuckabakpirinc_corbasi.jpg'),
  'kiymali_borek_rulolari': require('../assets/recipes/kuzu_kiyma_ile_sebzeli_eriste.jpg'),
  'kiymali_patates': require('../assets/recipes/avokado___patates.jpg'),
  'kiymali_bamya___eriste___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kiymali_bamya___pilav___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kiymali_bezelye___bulgur_pilavi': require('../assets/recipes/bezelye_puresi.jpg'),
  'kiymali_bezelye___bulgur_pilavi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kiymali_bezelye___pirinc_pilavi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kiymali_bezelye_yemegi': require('../assets/recipes/bezelye_yemegi.jpg'),
  'kiymali_brokoli_yemegi___eriste': require('../assets/recipes/kuzu_kiyma_ile_sebzeli_eriste.jpg'),
  'kiymali_enginar___eriste___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kiymali_kabak_yemegi___pirinc_pilavi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kiymali_nohut_yemegi___bulgur_pilavi': require('../assets/recipes/bulgurlu_yemek.jpg'),
  'kiymali_patates_oturtma___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kiymali_semizotu___bulgur_pilavi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kiymali_semizotu___eriste___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kiymali_semizotu_yemegi___bulgur_pilavi': require('../assets/recipes/kiymali_semizotu_yemegi.jpg'),
  'kiymali_semizotu_yemegi___bulgur_pilavi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kiymali_semizotu_yemegi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kiymali_taze_fasulye___eriste': require('../assets/recipes/kuzu_kiyma_ile_sebzeli_eriste.jpg'),
  'kiymali_taze_fasulye___pirinc_pilavi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kiymali_yesil_mercimek___bulgur_pilavi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kiymali_ispanak___eriste___yogurt': require('../assets/recipes/yogurt.jpg'),
  'kiymali_havuclu_bezelye_yemegi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'labne___muz___yulaf___ceviz': require('../assets/recipes/yumurta_sarisi_cirpma_labne.jpg'),
  'lor_peyniri': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'lor_peyniri___avokado': require('../assets/recipes/lor_peyniri___avokado.jpg'),
  'lor_peyniri___yumurta_sarisi': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'manti___yogurt': require('../assets/recipes/yogurt.jpg'),
  'maydanozlu_omlet___labne___salatalik': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'menemen___dil_peyniri___zeytin': require('../assets/recipes/domates_ve_yumurta_sarisi_menemen.jpg'),
  'menemen___kasar_peyniri___zeytin': require('../assets/recipes/domates_ve_yumurta_sarisi_menemen.jpg'),
  'menemen___lor___zeytin___avokado': require('../assets/recipes/domates_ve_yumurta_sarisi_menemen.jpg'),
  'menemen___lor_peyniri___zeytin': require('../assets/recipes/domates_ve_yumurta_sarisi_menemen.jpg'),
  'menemen_veya_omlet___peynir': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'mercimek_koftesi': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'mercimek_corbasi': require('../assets/recipes/mercimek_corbasi.jpg'),
  'mercimek_corbasi___tam_bugday_ekmegi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'mercimekli_bulgur_pilavi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'mevsim_meyve_salatasi': require('../assets/recipes/krep___lor___meyve.jpg'),
  'mevsim_baligi___mercimekli_bulgur_pilavi': require('../assets/recipes/mercimek_corbasi.jpg'),
  'mevsim_meyvesi___badem': require('../assets/recipes/krep___lor___meyve.jpg'),
  'meyve___kuruyemis': require('../assets/recipes/krep___lor___meyve.jpg'),
  'meyve_salatasi': require('../assets/recipes/krep___lor___meyve.jpg'),
  'mini_kofteler': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'muffin_lor_peyniri_biraz_salatalik_armut': require('../assets/recipes/sebzeli_muffin_kek.jpg'),
  'muz_ezmesi': require('../assets/recipes/muz_ezmesi.jpg'),
  'muzlu_yulaf_lapasi': require('../assets/recipes/muzlu_yulaf_lapasi.jpg'),
  'muzlu_yulaf_pankek': require('../assets/recipes/yumurta_sarisi_ile_pankek_toz_ceviz.jpg'),
  'mucver_kabak_koftesi': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'mucver___ayran': require('../assets/recipes/kuzu_kiymali_semizotlu_kabakli_havuclu_mucver.jpg'),
  'mucver___eriste': require('../assets/recipes/kuzu_kiymali_semizotlu_kabakli_havuclu_mucver.jpg'),
  'mucver___yogurt': require('../assets/recipes/yogurt.jpg'),
  'nohutlu_bugdayli_yogurt_corbasi': require('../assets/recipes/yogurt.jpg'),
  'omlet___avokado___bebek_biskuvisi': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'omlet___avokado___lor___bebek_biskuvisi': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'omlet___kasar___zeytin___avokado': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'omlet___salatalik___zeytin___findik_ezmesi': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'pancake_bebek_pankek': require('../assets/recipes/yumurta_sarisi_ile_pankek_toz_ceviz.jpg'),
  'pankek___labne___avokado___muz': require('../assets/recipes/yumurta_sarisi_ile_pankek_toz_ceviz.jpg'),
  'pankek___mevsim_meyvesi': require('../assets/recipes/yumurta_sarisi_ile_pankek_toz_ceviz.jpg'),
  'pankek___muz___ceviz___avokado': require('../assets/recipes/yumurta_sarisi_ile_pankek_toz_ceviz.jpg'),
  'pankek___muzlu_labneli_karisim': require('../assets/recipes/yumurta_sarisi_ile_pankek_toz_ceviz.jpg'),
  'pankek___tahin___mevsim_meyvesi': require('../assets/recipes/yumurta_sarisi_ile_pankek_toz_ceviz.jpg'),
  'patates___havuc_puresi': require('../assets/recipes/patates___havuc_puresi.jpg'),
  'patates___kabak___havuc_puresi': require('../assets/recipes/patates___kabak___havuc_puresi.jpg'),
  'patates_puresi': require('../assets/recipes/patates_puresi.jpg'),
  'patates_puresi_yogurt': require('../assets/recipes/patates_puresi.jpg'),
  'patates_brokoli_puresi': require('../assets/recipes/brokoli_puresi.jpg'),
  'patates_havuc_puresi': require('../assets/recipes/havuc_puresi.jpg'),
  'patatesli_havuc_corbasi': require('../assets/recipes/havuckabakpirinc_corbasi.jpg'),
  'patatesli_biberli_omlet___peynir___zeytin': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'patatesli_omlet___dil_peyniri___zeytin': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'patatesli_omlet___labne___salatalik': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'patatesli_omlet___lor___zeytin___salatalik': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'patatesli_peynirli_omlet___avokado': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'patatesli_yesillikli_omlet___dil_peyniri': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'peynirli_ispanak_boregi': require('../assets/recipes/ispanakpatates_puresi.jpg'),
  'peynirli_makarna': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'peynirli_omlet': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'peynirli_cirpma_yumurta___dil_peyniri': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'pilav___buharda_sebzeler___balik': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'pirinc_lapasi': require('../assets/recipes/pirinc_lapasi.jpg'),
  'pirincli_yayla_corbasi_kiyma_ile_kofte': require('../assets/recipes/pirincli_yayla_corbasi_kiyma_ile_kofte.jpg'),
  'pirincli_yogurt_corbasi': require('../assets/recipes/yogurt.jpg'),
  'sebzeli_bulgur_pilavi': require('../assets/recipes/bulgurlu_yemek.jpg'),
  'sebzeli_firin_patates': require('../assets/recipes/avokado___patates.jpg'),
  'sebzeli_makarna': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'sebzeli_omlet': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'sebzeli_yulaf_corbasi': require('../assets/recipes/havuckabakpirinc_corbasi.jpg'),
  'sebzeli_bebek_muffin___kasar___zeytin': require('../assets/recipes/sebzeli_muffin_kek.jpg'),
  'sebzeli_bezelye_yemegi___bulgur_pilavi': require('../assets/recipes/bezelye_yemegi.jpg'),
  'sebzeli_bezelye_yemegi___bulgur_pilavi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'sebzeli_bulgur_pilavi___balik_tadimi': require('../assets/recipes/bulgurlu_yemek.jpg'),
  'sebzeli_kofte___bulgur_pilavi': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'sebzeli_muffin___ayran': require('../assets/recipes/sebzeli_muffin_kek.jpg'),
  'sebzeli_muffin___dil_peyniri___avokado': require('../assets/recipes/sebzeli_muffin_kek.jpg'),
  'sebzeli_muffin___dil_peyniri___zeytin': require('../assets/recipes/sebzeli_muffin_kek.jpg'),
  'sebzeli_muffin___haslanmis_yumurta___peynir': require('../assets/recipes/sebzeli_muffin_kek.jpg'),
  'sebzeli_muffin___labne___salatalik': require('../assets/recipes/sebzeli_muffin_kek.jpg'),
  'sebzeli_muffin_kek_yumurta_sarisi_lor_peyniri_salatalik_elma': require('../assets/recipes/sebzeli_muffin_kek.jpg'),
  'sebzeli_mucver___labne___ceviz': require('../assets/recipes/kuzu_kiymali_semizotlu_kabakli_havuclu_mucver.jpg'),
  'sebzeli_omlet___labne___bebek_ekmegi': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'sebzeli_omlet___labne___zeytin': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'sebzeli_omlet___labne___zeytin___salatalik': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'sebzeli_pirasa_yemegi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'sebzeli_corek': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'sebzeli_irmik': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'semizotlu_kuzu_kiymali_pirincli_yemek___yogurt': require('../assets/recipes/yogurt.jpg'),
  'somonlu_kofte': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'sulu_kofte_corbasi___tam_bugday_ekmegi': require('../assets/recipes/havuckabakpirinc_corbasi.jpg'),
  'tadimi_yapilan_sebzeler_ile_muffin_yumurta_sarisi_ile_avokado_labne': require('../assets/recipes/sebzeli_muffin_kek.jpg'),
  'tam_bugday_unlu_sebze_kofte___patates_puresi___yogurt': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'tarhana_corbasi': require('../assets/recipes/havuckabakpirinc_corbasi.jpg'),
  'tarhana_corbasi___manti___yogurt': require('../assets/recipes/yogurt.jpg'),
  'tarhana_corbasi___tam_bugday_ekmegi': require('../assets/recipes/havuckabakpirinc_corbasi.jpg'),
  'tarhana_corbasi___tam_bugday_ekmegi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'tarhana_corbasi___tavuklu_eriste': require('../assets/recipes/havuckabakpirinc_corbasi.jpg'),
  'tarhanali_omlet___dil_peyniri___avokado': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'tarhanali_omlet___dil_peyniri___avokado___elma': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'tarhanali_omlet___dil_peyniri___zeytin': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'tarhanali_omlet___labne___zeytin___avokado': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'tarhanali_omlet___lor___pogaca': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'tarhanali_omlet___salatalik___avokado': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'tatli_patates_ezmesi': require('../assets/recipes/tatli_patates_ezmesi.jpg'),
  'tatli_patates_puresi': require('../assets/recipes/tatli_patates_puresi.jpg'),
  'tatli_patates_puresi___pirinc_tadimlik_yogurt': require('../assets/recipes/patates_puresi.jpg'),
  'tatli_patatesli_kasarli_omlet___lor___salatalik': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'tatli_patatesli_kabakli_ve_kiymali_sebze_yemegi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'tatli_patatesli_tadimlik_semizotu_ve_kuzu_kiymali_yemek___yogurt': require('../assets/recipes/yogurt.jpg'),
  'tavuk_suyu_corbasi': require('../assets/recipes/havuckabakpirinc_corbasi.jpg'),
  'tavuk_but___sebzeli_makarna___yogurt': require('../assets/recipes/yogurt.jpg'),
  'tavuk_buglama___eriste': require('../assets/recipes/kuzu_kiyma_ile_sebzeli_eriste.jpg'),
  'tavuk_haslama___sebzeler___yogurt': require('../assets/recipes/yogurt.jpg'),
  'tavuk_koftesi___sebzeli_eriste': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'tavuk_koftesi___sebzeli_makarna___yogurt': require('../assets/recipes/yogurt.jpg'),
  'tavuk_sote___bulgur_pilavi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'tavuk_sote___sebzeli_eriste': require('../assets/recipes/kuzu_kiyma_ile_sebzeli_eriste.jpg'),
  'tavuk_sote___sebzeli_makarna': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'tavuk_suyuna_tel_sehriye_corbasi___sebzeler': require('../assets/recipes/havuckabakpirinc_corbasi.jpg'),
  'tavuklu_pirinc_corbasi': require('../assets/recipes/havuckabakpirinc_corbasi.jpg'),
  'tavuklu_sebze_pilav': require('../assets/recipes/tam_bugday_unlu_sebze_kofte.jpg'),
  'tavuklu_sebze_corbasi': require('../assets/recipes/havuckabakpirinc_corbasi.jpg'),
  'tavuklu_bezelye___eriste___yogurt': require('../assets/recipes/yogurt.jpg'),
  'tavuklu_bezelye___pirinc_pilavi': require('../assets/recipes/bezelye_puresi.jpg'),
  'tavuklu_bezelye_yemegi___eriste': require('../assets/recipes/bezelye_yemegi.jpg'),
  'tavuklu_mercimekli_bulgur_pilavi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'taze_fasulye___pilav___cacik': require('../assets/recipes/yesil_fasulye_yemegi.jpg'),
  'taze_meyve___kuruyemis': require('../assets/recipes/krep___lor___meyve.jpg'),
  'taze_patates_puresi___tavuk_kofte___yogurt': require('../assets/recipes/patates_puresi.jpg'),
  'yayla_corbasi___kuzu_kofte': require('../assets/recipes/havuckabakpirinc_corbasi.jpg'),
  'yayla_corbasi_pirincli_ve_tadimlik_semizotlu': require('../assets/recipes/yayla_corbasi_pirincli.jpg'),
  'yesil_fasulye_yemegi_domatesli_pirinc_pilavi___yogurt': require('../assets/recipes/yesil_fasulye_yemegi.jpg'),
  'yesil_fasulye_corbasi_kiymali_domatesli___yogurt': require('../assets/recipes/yogurt.jpg'),
  'yesil_mercimek_yemegi___yogurt': require('../assets/recipes/yogurt.jpg'),
  'yesil_mercimek_yemegi_kiymali___yogurt': require('../assets/recipes/yogurt.jpg'),
  'yogurt': require('../assets/recipes/yogurt.jpg'),
  'yogurt___kabak___patates_puresi': require('../assets/recipes/yogurt___kabak___patates_puresi.jpg'),
  'yogurt___mevsim_meyvesi': require('../assets/recipes/yogurt.jpg'),
  'yogurt___mevsim_meyvesi___ceviz': require('../assets/recipes/yogurt.jpg'),
  'yogurt___patates_puresi': require('../assets/recipes/yogurt___patates_puresi.jpg'),
  'yogurt_corbasi_tel_sehriye_ile': require('../assets/recipes/yogurt.jpg'),
  'yogurtlu_havuc_ezmesi': require('../assets/recipes/yogurt.jpg'),
  'yogurtlu_ispanak': require('../assets/recipes/yogurt.jpg'),
  'yogurtlu_kabak': require('../assets/recipes/yogurtlu_kabak.jpg'),
  'yogurtlu_meyve_ezmesi': require('../assets/recipes/yogurt.jpg'),
  'yogurtlu_sebze_salatasi': require('../assets/recipes/yogurt.jpg'),
  'yulaf___elma___ceviz___tarcin': require('../assets/recipes/elma___avokado_yogurt.jpg'),
  'yulaf_lapasi___yumurta_sarisi___armut_puresi': require('../assets/recipes/yumurta_sarisi___armut_puresi.jpg'),
  'yulaf_lapasi___yumurta_sarisi___lor_peyniri': require('../assets/recipes/yulaf_lapasi___yumurta_sarisi___lor_peyniri.jpg'),
  'yulaf_unu_ile_yogurt_corbasi': require('../assets/recipes/yulaf_unu_ile_yogurt_corbasi.jpg'),
  'yulafli_kasar_peynirli_tost___salatalik': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'yumurta___labne___elma_puresi': require('../assets/recipes/elma_puresi.jpg'),
  'yumurta___labne___pekmez': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'yumurta___lor_peyniri___salatalik': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'yumurta_sarili_havuc': require('../assets/recipes/kuzu_kiymali_semizotlu_kabakli_havuclu_mucver.jpg'),
  'yumurta_sarili_ispanak': require('../assets/recipes/ispanakpatates_puresi.jpg'),
  'yumurta_sarisi': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'yumurta_sarisi_cirpma_labne_peyniri_salatalik_muz': require('../assets/recipes/yumurta_sarisi_cirpma_labne.jpg'),
  'yumurta_sarisi___armut_puresi': require('../assets/recipes/yumurta_sarisi___armut_puresi.jpg'),
  'yumurta_sarisi___labne_haslanmis_yulaf_ezmesi___armut___toz_ceviz': require('../assets/recipes/yumurta_sarisi___armut_puresi.jpg'),
  'yumurta_sarisi___patates_puresi': require('../assets/recipes/patates_puresi.jpg'),
  'yumurta_sarisi_ile_krep_tam_bugday_unu_avokado_ve_labne_surulerek___elma': require('../assets/recipes/yumurta_sarisi_ile_krep.jpg'),
  'yumurta_sarisi_ile_krep_tam_bugday_unu_avokado_ve_labne_surulerek___muz___toz_ceviz': require('../assets/recipes/yumurta_sarisi_ile_krep.jpg'),
  'yumurta_sarisi_ile_krep_lor_peyniri_ve_avokadodan_sos_surulerek': require('../assets/recipes/yumurta_sarisi_ile_krep.jpg'),
  'yumurta_sarisi_ile_omlet_lor_peyniri_salatalik': require('../assets/recipes/yumurta_sarisi_ile_omlet_lor.jpg'),
  'yumurta_sarisi_ile_pankek_avokado___muz___labne_karisimi_uzerine_surulerek': require('../assets/recipes/yumurta_sarisi_ile_pankek_avokado.jpg'),
  'yumurta_sarisi_ile_pankek_toz_ceviz___labne___muz___pekmez': require('../assets/recipes/yumurta_sarisi_ile_pankek_toz_ceviz.jpg'),
  'yumurta_sarisi_ile_pankek_toz_ceviz___lor___muz___pekmez': require('../assets/recipes/yumurta_sarisi_ile_pankek_toz_ceviz.jpg'),
  'yumurta_sarisi_ile_pankek_uzerine_pekmez_ve_muz_yanina_labne_ve_avokado': require('../assets/recipes/yumurta_sarisi_ile_pankek_toz_ceviz.jpg'),
  'yumurta_sarisi_ile_tarhanali_omlet_kuru_kayisi___toz_ceviz_labne_avokado': require('../assets/recipes/yumurta_sarisi_ile_tarhanali_omlet.jpg'),
  'yumurta_sarisi_ve_avokado_puresi_ile_lor_peyniri___toz_ceviz_muz': require('../assets/recipes/yumurta_sarisi_ve_avokado.jpg'),
  'yumurta_sarisi_ve_labne_peyniri_bebek_irmigi_ile_meyve_puresi_toz_ceviz_ve_pekmez': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'yumurta_sarisi_ve_lor_peyniri_bebek_irmigi_ile_meyve_puresi_toz_ceviz_ve_pekmez': require('../assets/recipes/yumurta_sarisi_ve_lor_peyniri.jpg'),
  'yumurta_sarisi_ev_yapimi_kek_veya_bebe_biskuvisi_labne___kuru_kayisi': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'yumurta_sarisi_labne_peyniri_salatalik_elma___toz_ceviz': require('../assets/recipes/elma___avokado_yogurt.jpg'),
  'yumurta_sarisi_lor_peyniri_gun_kurusu___toz_ceviz_avokado': require('../assets/recipes/elma___avokado_yogurt.jpg'),
  'yumurta_sarisi_pisirilmis_yulaf_icine_labne_ve_gun_kurusu_ezmesi': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'yumurtali_fincan_kek___kasar___zeytin': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'yumurtali_tam_bugday_ekmegi___lor___salatalik': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'corba___manti___yogurt': require('../assets/recipes/yogurt.jpg'),
  'cirpma_yumurta_biberli___lor___domates': require('../assets/recipes/lor_peyniri___yumurta_sarisi.jpg'),
  'seftalili_pirinc_puresi': require('../assets/recipes/seftalili_pirinc_puresi.jpg'),
};

function normalizeKey(title: string): string {
  return title
    .toLowerCase()
    .replace(/\s+/g, '_')
    .replace(/ş/g, 's').replace(/ç/g, 'c').replace(/ğ/g, 'g')
    .replace(/ı/g, 'i').replace(/ö/g, 'o').replace(/ü/g, 'u')
    .replace(/[+\/\-(),;']/g, '_')
    .replace(/_+/g, '_')
    .replace(/_$/g, '');
}

export function getLocalRecipeImage(title: string): any | undefined {
  const key = normalizeKey(title);
  
  // Tam eşleşme
  if (RECIPE_IMAGE_MAP[key]) return RECIPE_IMAGE_MAP[key];
  
  // Kısmi eşleşme
  for (const [mapKey, img] of Object.entries(RECIPE_IMAGE_MAP)) {
    if (key.includes(mapKey) || mapKey.includes(key)) return img;
  }
  
  // Anahtar kelime fallback
  const keywords = ['omlet', 'corba', 'pilav', 'makarna', 'kofte', 'pankek', 'krep',
    'muffin', 'avokado', 'kabak', 'havuc', 'patates', 'elma', 'armut', 'muz',
    'yumurta', 'yogurt', 'tavuk', 'balik', 'kiyma', 'mercimek', 'bulgur',
    'ispanak', 'brokoli', 'bezelye', 'nohut', 'peynir'];
  for (const kw of keywords) {
    if (key.includes(kw)) {
      for (const [mapKey, img] of Object.entries(RECIPE_IMAGE_MAP)) {
        if (mapKey.includes(kw)) return img;
      }
    }
  }
  
  return undefined;
}

export const RECIPE_IMAGE_COUNT = 344;
