/**
 * Kaşık — Türk Bebek Ek Gıda Tarif Veritabanı
 * 36 tarif: 6+ ay, 8+ ay, 12+ ay kategorilerinde
 * Her tarif: malzemeler, adımlar, besin değerleri, alerjen bilgisi, ipucu
 */

import { AllergenType } from '../types';
import { EXTRA_RECIPES_6M, EXTRA_RECIPES_8M, EXTRA_RECIPES_12M } from './recipesExtra';

export interface RecipeIngredient {
  name: string;
  amount: number;
  unit: string;
  emoji: string;
  isAllergen?: boolean;
}

export interface RecipeNutrient {
  name: string;
  value: number;
  unit: string;
}

export interface RecipeData {
  id: string;
  title: string;
  description: string;
  emoji: string;
  ageGroup: '6m' | '8m' | '12m+';
  prepTime: number;
  calories: number;
  servings: number;
  difficulty: 'easy' | 'medium' | 'hard';
  rating: { average: number; count: number };
  likes: number;
  views: number;
  comments: number;
  isLiked: boolean;
  isAIGenerated: boolean;
  source: 'official' | 'community' | 'ai';
  authorName: string;
  authorVerified: boolean;
  allergens: AllergenType[];
  tags: string[];
  ingredients: RecipeIngredient[];
  steps: string[];
  nutrients: RecipeNutrient[];
  tip: string;
  createdAt: Date;
  photoURL?: string | null;
}

const hoursAgo = (h: number) => new Date(Date.now() - h * 60 * 60 * 1000);

// =============================================
// 6+ AY TARİFLERİ (İlk Ek Gıdalar — Püreler)
// =============================================

const RECIPES_6M: RecipeData[] = [
  {
    id: '1',
    title: 'Elmalı Pirinç Püresi',
    description: 'Tatlı ve besleyici, ilk ek gıdalara mükemmel bir başlangıç.',
    emoji: '🥣',
    ageGroup: '6m',
    prepTime: 15,
    calories: 90,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.8, count: 32 },
    likes: 124,
    views: 890,
    comments: 18,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: [],
    tags: ['Kolay', 'İlk Ek Gıda'],
    ingredients: [
      { name: 'Pirinç', amount: 2, unit: 'yemek kaşığı', emoji: '🍚' },
      { name: 'Elma', amount: 1, unit: 'küçük', emoji: '🍎' },
      { name: 'Su', amount: 200, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Pirinci yıkayıp bir tencereye alın.',
      'Elmayı soyun, çekirdeklerini çıkarıp küçük parçalara bölün.',
      'Su ekleyip kısık ateşte 15 dakika pişirin.',
      'Blender ile pürüzsüz kıvama getirin.',
      'Ilık olarak servis edin.',
    ],
    nutrients: [
      { name: 'Karbonhidrat', value: 18, unit: 'g' },
      { name: 'Lif', value: 2, unit: 'g' },
      { name: 'C Vitamini', value: 6, unit: 'mg' },
      { name: 'Demir', value: 0.8, unit: 'mg' },
    ],
    tip: 'İlk denemede sadece pirinç püresi ile başlayıp, birkaç gün sonra elma ekleyebilirsiniz.',
    createdAt: hoursAgo(48),
  },
  {
    id: '3',
    title: 'Tatlı Patates Ezmesi',
    description: 'Doğal tatlı, A vitamini zengini basit bir püre.',
    emoji: '🍠',
    ageGroup: '6m',
    prepTime: 25,
    calories: 110,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.9, count: 45 },
    likes: 203,
    views: 1500,
    comments: 42,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: [],
    tags: ['Kolay', 'A Vitamini'],
    ingredients: [
      { name: 'Tatlı Patates', amount: 1, unit: 'orta', emoji: '🍠' },
      { name: 'Anne sütü veya formül', amount: 2, unit: 'yemek kaşığı', emoji: '🍼' },
    ],
    steps: [
      'Tatlı patateyi yıkayıp kabuğunu soyun.',
      'Küçük küpler halinde kesin.',
      'Buharda 20 dakika pişirin.',
      'Çatalla ezin, anne sütü ekleyip pürüzsüz yapın.',
    ],
    nutrients: [
      { name: 'A Vitamini', value: 250, unit: 'mcg' },
      { name: 'Lif', value: 3, unit: 'g' },
      { name: 'C Vitamini', value: 15, unit: 'mg' },
      { name: 'Potasyum', value: 200, unit: 'mg' },
    ],
    tip: 'Tatlı patates kendi doğal tatlılığıyla bebekler tarafından çok sevilir.',
    createdAt: hoursAgo(168),
  },
  {
    id: '6',
    title: 'Mercimek Çorbası',
    description: 'Türk mutfağının klasiği, demir ve protein deposu.',
    emoji: '🫘',
    ageGroup: '6m',
    prepTime: 35,
    calories: 85,
    servings: 2,
    difficulty: 'easy',
    rating: { average: 4.6, count: 28 },
    likes: 142,
    views: 780,
    comments: 22,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: [],
    tags: ['Demir ↑', 'Protein', 'Türk Mutfağı'],
    ingredients: [
      { name: 'Kırmızı Mercimek', amount: 3, unit: 'yemek kaşığı', emoji: '🫘' },
      { name: 'Havuç', amount: 1, unit: 'küçük', emoji: '🥕' },
      { name: 'Patates', amount: 1, unit: 'küçük', emoji: '🥔' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
      { name: 'Su', amount: 300, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Mercimeği yıkayıp süzün.',
      'Havuç ve patateyi soyup küçük doğrayın.',
      'Tüm malzemeleri tencereye koyup su ekleyin.',
      'Kaynayınca kısık ateşte 25 dakika pişirin.',
      'Blender ile pürüzsüz yapın. Zeytinyağı ekleyin.',
    ],
    nutrients: [
      { name: 'Demir', value: 3, unit: 'mg' },
      { name: 'Protein', value: 5, unit: 'g' },
      { name: 'Lif', value: 4, unit: 'g' },
      { name: 'A Vitamini', value: 80, unit: 'mcg' },
    ],
    tip: 'Mercimek çorbası dondurucuda 1 ay saklanabilir. Buz kalıplarına döküp porsiyon porsiyon dondurun.',
    createdAt: hoursAgo(6),
  },
  {
    id: '5',
    title: 'Muzlu Yulaf Lapası',
    description: 'Enerjik ve lif zengini bir kahvaltı alternatifi.',
    emoji: '🍌',
    ageGroup: '6m',
    prepTime: 10,
    calories: 120,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.7, count: 38 },
    likes: 178,
    views: 1200,
    comments: 28,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: ['wheat'],
    tags: ['Kolay', 'Lif', 'Kahvaltı'],
    ingredients: [
      { name: 'Yulaf', amount: 2, unit: 'yemek kaşığı', emoji: '🥣' },
      { name: 'Muz', amount: 0.5, unit: 'adet', emoji: '🍌' },
      { name: 'Su', amount: 100, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Yulafı su ile karıştırıp kısık ateşte 5 dakika pişirin.',
      'Muzu çatalla iyice ezin.',
      'Pişen yulafa ezmiş muzu ekleyin.',
      'İyice karıştırıp ılık servis edin.',
    ],
    nutrients: [
      { name: 'Lif', value: 3, unit: 'g' },
      { name: 'Demir', value: 1.5, unit: 'mg' },
      { name: 'B6 Vitamini', value: 0.3, unit: 'mg' },
      { name: 'Potasyum', value: 180, unit: 'mg' },
    ],
    tip: 'Yulaf gluten içerir. İlk denemede az miktarla başlayın ve reaksiyon takibi yapın.',
    createdAt: hoursAgo(96),
  },
  {
    id: '7',
    title: 'Havuç Püresi',
    description: 'Beta karoten zengini, tatlı ve yumuşacık ilk püre.',
    emoji: '🥕',
    ageGroup: '6m',
    prepTime: 20,
    calories: 45,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.5, count: 52 },
    likes: 167,
    views: 1100,
    comments: 15,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: [],
    tags: ['Kolay', 'İlk Ek Gıda', 'A Vitamini'],
    ingredients: [
      { name: 'Havuç', amount: 2, unit: 'orta', emoji: '🥕' },
      { name: 'Su', amount: 150, unit: 'ml', emoji: '💧' },
      { name: 'Zeytinyağı', amount: 0.5, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Havuçları soyup ince halkalar halinde kesin.',
      'Tencereye alıp su ekleyin.',
      'Kısık ateşte 15 dakika yumuşayana kadar pişirin.',
      'Blender ile pürüzsüz kıvama getirin.',
      'Zeytinyağı ekleyip karıştırın.',
    ],
    nutrients: [
      { name: 'A Vitamini', value: 450, unit: 'mcg' },
      { name: 'Lif', value: 2.5, unit: 'g' },
      { name: 'C Vitamini', value: 5, unit: 'mg' },
      { name: 'Potasyum', value: 160, unit: 'mg' },
    ],
    tip: 'Havuç en iyi ilk ek gıdalardan biridir. Doğal tatlılığı sayesinde bebekler tarafından genellikle çok sevilir.',
    createdAt: hoursAgo(200),
  },
  {
    id: '8',
    title: 'Kabak Püresi',
    description: 'Hafif ve sindirimi kolay, ilk günler için ideal.',
    emoji: '🎃',
    ageGroup: '6m',
    prepTime: 20,
    calories: 35,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.3, count: 29 },
    likes: 98,
    views: 620,
    comments: 8,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: [],
    tags: ['Kolay', 'İlk Ek Gıda', 'Hafif'],
    ingredients: [
      { name: 'Kabak', amount: 1, unit: 'küçük', emoji: '🎃' },
      { name: 'Su', amount: 100, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Kabağı soyup çekirdeklerini çıkarın.',
      'Küçük parçalara bölün.',
      'Buharda 15 dakika pişirin.',
      'Çatalla ezin veya blenderdan geçirin.',
    ],
    nutrients: [
      { name: 'C Vitamini', value: 8, unit: 'mg' },
      { name: 'Lif', value: 1.5, unit: 'g' },
      { name: 'Potasyum', value: 130, unit: 'mg' },
      { name: 'Magnezyum', value: 10, unit: 'mg' },
    ],
    tip: 'Kabak çok sulu olduğu için fazla su eklemeyin. Kendi suyu yeterli olabilir.',
    createdAt: hoursAgo(240),
  },
  {
    id: '9',
    title: 'Armut Püresi',
    description: 'Tatlı ve yumuşak, kabızlığa iyi gelen doğal lif kaynağı.',
    emoji: '🍐',
    ageGroup: '6m',
    prepTime: 15,
    calories: 60,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.6, count: 34 },
    likes: 145,
    views: 830,
    comments: 11,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: [],
    tags: ['Kolay', 'Lif', 'İlk Ek Gıda'],
    ingredients: [
      { name: 'Armut', amount: 1, unit: 'olgun', emoji: '🍐' },
      { name: 'Su', amount: 50, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Armudu soyup çekirdeklerini çıkarın.',
      'Küçük parçalara bölün.',
      'Buharda 10 dakika yumuşatın.',
      'Çatalla ezin veya blenderdan geçirin.',
    ],
    nutrients: [
      { name: 'Lif', value: 3, unit: 'g' },
      { name: 'C Vitamini', value: 4, unit: 'mg' },
      { name: 'Potasyum', value: 100, unit: 'mg' },
      { name: 'Karbonhidrat', value: 14, unit: 'g' },
    ],
    tip: 'Armut kabızlık sorununa doğal bir çözümdür. Olgun armut kullanırsanız pişirmeden de ezebilirsiniz.',
    createdAt: hoursAgo(300),
  },
  {
    id: '10',
    title: 'Bezelye Püresi',
    description: 'Protein ve demir deposu yeşil süper gıda.',
    emoji: '🟢',
    ageGroup: '6m',
    prepTime: 15,
    calories: 65,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.1, count: 22 },
    likes: 87,
    views: 490,
    comments: 9,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: [],
    tags: ['Protein', 'Demir ↑', 'Kolay'],
    ingredients: [
      { name: 'Bezelye (taze veya dondurulmuş)', amount: 100, unit: 'g', emoji: '🟢' },
      { name: 'Su', amount: 100, unit: 'ml', emoji: '💧' },
      { name: 'Zeytinyağı', amount: 0.5, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Bezelyeleri kaynar suda 10 dakika haşlayın.',
      'Süzüp blenderdan geçirin.',
      'Kabuklar kaldıysa süzgeçten geçirin.',
      'Zeytinyağı ekleyip servis edin.',
    ],
    nutrients: [
      { name: 'Protein', value: 4, unit: 'g' },
      { name: 'Demir', value: 1.5, unit: 'mg' },
      { name: 'Lif', value: 4, unit: 'g' },
      { name: 'C Vitamini', value: 20, unit: 'mg' },
    ],
    tip: 'Bezelye kabuğu sindirimi zorlaştırabilir. Süzgeçten geçirerek kabuklarını ayıklayın.',
    createdAt: hoursAgo(350),
  },
  {
    id: '11',
    title: 'Avokado Ezmesi',
    description: 'Sağlıklı yağlar ve potasyum zengini süper besin.',
    emoji: '🥑',
    ageGroup: '6m',
    prepTime: 5,
    calories: 80,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.4, count: 41 },
    likes: 156,
    views: 950,
    comments: 19,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: [],
    tags: ['Kolay', 'Omega-3', 'Pişirme Yok'],
    ingredients: [
      { name: 'Avokado', amount: 0.5, unit: 'olgun', emoji: '🥑' },
      { name: 'Anne sütü veya formül', amount: 1, unit: 'yemek kaşığı', emoji: '🍼' },
    ],
    steps: [
      'Olgun avokadoyu ikiye bölüp çekirdeğini çıkarın.',
      'Kaşıkla içini çıkarın.',
      'Çatalla iyice ezin.',
      'Anne sütü ekleyip kıvamını ayarlayın.',
    ],
    nutrients: [
      { name: 'Sağlıklı Yağ', value: 7, unit: 'g' },
      { name: 'Potasyum', value: 250, unit: 'mg' },
      { name: 'Lif', value: 3, unit: 'g' },
      { name: 'E Vitamini', value: 1, unit: 'mg' },
    ],
    tip: 'Avokado çok çabuk kararır. Hazırladıktan hemen sonra servis edin. Limon suyu renk değişimini yavaşlatır.',
    createdAt: hoursAgo(120),
  },
  {
    id: '12',
    title: 'Patates-Havuç Püresi',
    description: 'Klasik kombinasyon, doyurucu ve besleyici.',
    emoji: '🥔',
    ageGroup: '6m',
    prepTime: 25,
    calories: 95,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.7, count: 56 },
    likes: 189,
    views: 1300,
    comments: 24,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: [],
    tags: ['Kolay', 'Doyurucu', 'İlk Ek Gıda'],
    ingredients: [
      { name: 'Patates', amount: 1, unit: 'küçük', emoji: '🥔' },
      { name: 'Havuç', amount: 1, unit: 'küçük', emoji: '🥕' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
      { name: 'Su', amount: 200, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Patates ve havucu soyup küçük küpler halinde kesin.',
      'Tencereye alıp su ekleyin.',
      'Kısık ateşte 20 dakika pişirin.',
      'Blender ile pürüzsüz kıvama getirin.',
      'Zeytinyağı ekleyip karıştırın.',
    ],
    nutrients: [
      { name: 'Karbonhidrat', value: 20, unit: 'g' },
      { name: 'A Vitamini', value: 200, unit: 'mcg' },
      { name: 'Potasyum', value: 250, unit: 'mg' },
      { name: 'C Vitamini', value: 10, unit: 'mg' },
    ],
    tip: 'Kıvamı ayarlamak için pişirme suyunu saklayın. Çok koyu olursa biraz ekleyin.',
    createdAt: hoursAgo(380),
  },
  {
    id: '13',
    title: 'Erik Püresi',
    description: 'Kabızlığa birebir, doğal laksatif etkili meyve püresi.',
    emoji: '🟣',
    ageGroup: '6m',
    prepTime: 15,
    calories: 50,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.2, count: 18 },
    likes: 76,
    views: 420,
    comments: 6,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: [],
    tags: ['Lif', 'Kabızlık', 'Kolay'],
    ingredients: [
      { name: 'Kuru Erik', amount: 5, unit: 'adet', emoji: '🟣' },
      { name: 'Su', amount: 150, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Kuru erikleri sıcak suda 30 dakika bekletin.',
      'Yumuşayan erikleri suyu ile birlikte blenderdan geçirin.',
      'Pürüzsüz olana kadar çekin.',
      'Ilık olarak servis edin.',
    ],
    nutrients: [
      { name: 'Lif', value: 5, unit: 'g' },
      { name: 'Demir', value: 1, unit: 'mg' },
      { name: 'Potasyum', value: 150, unit: 'mg' },
      { name: 'K Vitamini', value: 8, unit: 'mcg' },
    ],
    tip: 'Erik püresi kabızlık sorunu yaşayan bebekler için doğal bir çözümdür. Günde 1-2 kaşık yeterlidir.',
    createdAt: hoursAgo(400),
  },
];

// =============================================
// 8+ AY TARİFLERİ (Karışık Püreler & İlk Dokular)
// =============================================

const RECIPES_8M: RecipeData[] = [
  {
    id: '2',
    title: 'Brokoli Çorbası',
    description: 'Demir ve C vitamini deposu, besleyici bir çorba.',
    emoji: '🥦',
    ageGroup: '8m',
    prepTime: 20,
    calories: 75,
    servings: 2,
    difficulty: 'medium',
    rating: { average: 4.2, count: 18 },
    likes: 89,
    views: 420,
    comments: 7,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: [],
    tags: ['Orta', 'Demir ↑'],
    ingredients: [
      { name: 'Brokoli', amount: 4, unit: 'çiçek', emoji: '🥦' },
      { name: 'Patates', amount: 1, unit: 'küçük', emoji: '🥔' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
      { name: 'Su', amount: 250, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Brokoli çiçeklerini ayırın, patateyi soyup küçük doğrayın.',
      'Tencereye su ekleyip kaynatın.',
      'Sebzeleri ekleyip kısık ateşte 15 dakika pişirin.',
      'Blender ile pürüzsüz kıvama getirin.',
      'Zeytinyağı ekleyip karıştırın.',
    ],
    nutrients: [
      { name: 'Protein', value: 3, unit: 'g' },
      { name: 'C Vitamini', value: 45, unit: 'mg' },
      { name: 'Demir', value: 1.5, unit: 'mg' },
      { name: 'Kalsiyum', value: 40, unit: 'mg' },
    ],
    tip: 'Brokoli sapları da kullanılabilir, daha fazla lif içerir.',
    createdAt: hoursAgo(12),
  },
  {
    id: '14',
    title: 'Yoğurtlu Havuç Ezmesi',
    description: 'Probiyotik ve beta karoten bir arada.',
    emoji: '🥕',
    ageGroup: '8m',
    prepTime: 20,
    calories: 80,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.5, count: 33 },
    likes: 134,
    views: 780,
    comments: 14,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: ['milk'],
    tags: ['Probiyotik', 'A Vitamini', 'Kolay'],
    ingredients: [
      { name: 'Havuç', amount: 1, unit: 'orta', emoji: '🥕' },
      { name: 'Yoğurt (tam yağlı)', amount: 2, unit: 'yemek kaşığı', emoji: '🥛' },
      { name: 'Zeytinyağı', amount: 0.5, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Havucu soyup rendeleyin veya küçük doğrayın.',
      'Buharda 15 dakika pişirin.',
      'Çatalla iyice ezin.',
      'Ilık yoğurt ve zeytinyağı ekleyip karıştırın.',
    ],
    nutrients: [
      { name: 'A Vitamini', value: 300, unit: 'mcg' },
      { name: 'Kalsiyum', value: 60, unit: 'mg' },
      { name: 'Protein', value: 2, unit: 'g' },
      { name: 'Probiyotik', value: 1, unit: 'milyar' },
    ],
    tip: 'Yoğurdu havuç soğuyunca ekleyin. Sıcak havuca eklenen yoğurt kesilir.',
    createdAt: hoursAgo(72),
  },
  {
    id: '15',
    title: 'Tavuk Suyu Çorbası',
    description: 'Protein zengini, bağışıklığı destekleyen klasik çorba.',
    emoji: '🍗',
    ageGroup: '8m',
    prepTime: 40,
    calories: 95,
    servings: 2,
    difficulty: 'medium',
    rating: { average: 4.7, count: 42 },
    likes: 198,
    views: 1350,
    comments: 31,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: [],
    tags: ['Protein', 'Bağışıklık', 'Türk Mutfağı'],
    ingredients: [
      { name: 'Tavuk göğsü', amount: 50, unit: 'g', emoji: '🍗' },
      { name: 'Havuç', amount: 1, unit: 'küçük', emoji: '🥕' },
      { name: 'Patates', amount: 1, unit: 'küçük', emoji: '🥔' },
      { name: 'Pirinç', amount: 1, unit: 'yemek kaşığı', emoji: '🍚' },
      { name: 'Su', amount: 400, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Tavuğu haşlayıp didikleyin.',
      'Sebzeleri soyup küçük doğrayın.',
      'Pirinci yıkayın.',
      'Tüm malzemeleri tavuk suyuna ekleyin.',
      'Kısık ateşte 25 dakika pişirip blenderdan geçirin.',
    ],
    nutrients: [
      { name: 'Protein', value: 10, unit: 'g' },
      { name: 'Demir', value: 1, unit: 'mg' },
      { name: 'Çinko', value: 1.5, unit: 'mg' },
      { name: 'B12 Vitamini', value: 0.3, unit: 'mcg' },
    ],
    tip: 'Tavuk suyunu fazla yapıp buz kalıplarında saklayabilirsiniz. Diğer tariflerde de kullanırsınız.',
    createdAt: hoursAgo(36),
  },
  {
    id: '16',
    title: 'Yumurta Sarılı Ispanak',
    description: 'Demir emilimini artıran mükemmel kombinasyon.',
    emoji: '🥬',
    ageGroup: '8m',
    prepTime: 15,
    calories: 85,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.3, count: 25 },
    likes: 112,
    views: 640,
    comments: 16,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: ['egg'],
    tags: ['Demir ↑', 'Protein', 'Kolay'],
    ingredients: [
      { name: 'Ispanak', amount: 1, unit: 'avuç', emoji: '🥬' },
      { name: 'Yumurta sarısı', amount: 1, unit: 'adet', emoji: '🥚' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Ispanağı iyice yıkayıp haşlayın (3 dk).',
      'Yumurta sarısını ayrı olarak haşlayın.',
      'Ispanağı süzüp doğrayın.',
      'Yumurta sarısını çatalla ezin.',
      'İkisini karıştırıp zeytinyağı ekleyin.',
    ],
    nutrients: [
      { name: 'Demir', value: 3.5, unit: 'mg' },
      { name: 'Protein', value: 4, unit: 'g' },
      { name: 'Kalsiyum', value: 50, unit: 'mg' },
      { name: 'K Vitamini', value: 120, unit: 'mcg' },
    ],
    tip: 'Ispanaktaki demir bitkisel olduğu için emilimi düşüktür. Yumurta sarısı ve limon emilimi artırır.',
    createdAt: hoursAgo(84),
  },
  {
    id: '17',
    title: 'Karnabahar Püresi',
    description: 'Hafif ve besleyici, beyaz sebze alternatifi.',
    emoji: '🥦',
    ageGroup: '8m',
    prepTime: 20,
    calories: 40,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.0, count: 15 },
    likes: 65,
    views: 380,
    comments: 5,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: [],
    tags: ['Hafif', 'C Vitamini', 'Kolay'],
    ingredients: [
      { name: 'Karnabahar', amount: 5, unit: 'çiçek', emoji: '🥦' },
      { name: 'Patates', amount: 0.5, unit: 'küçük', emoji: '🥔' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
      { name: 'Su', amount: 150, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Karnabahar çiçeklerini ayırıp yıkayın.',
      'Patateyi soyup küçük küpler halinde kesin.',
      'Buharda 15 dakika pişirin.',
      'Blenderdan geçirip zeytinyağı ekleyin.',
    ],
    nutrients: [
      { name: 'C Vitamini', value: 35, unit: 'mg' },
      { name: 'Lif', value: 2, unit: 'g' },
      { name: 'K Vitamini', value: 10, unit: 'mcg' },
      { name: 'Folat', value: 30, unit: 'mcg' },
    ],
    tip: 'Karnabahar gaz yapabilir. İlk seferde az miktarla başlayın.',
    createdAt: hoursAgo(150),
  },
  {
    id: '18',
    title: 'Sebzeli Bulgur Pilavı',
    description: 'Türk mutfağı klasiği, lif ve demir zengini.',
    emoji: '🌾',
    ageGroup: '8m',
    prepTime: 25,
    calories: 110,
    servings: 2,
    difficulty: 'medium',
    rating: { average: 4.4, count: 30 },
    likes: 128,
    views: 720,
    comments: 13,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: ['wheat'],
    tags: ['Türk Mutfağı', 'Demir ↑', 'Lif'],
    ingredients: [
      { name: 'İnce Bulgur', amount: 2, unit: 'yemek kaşığı', emoji: '🌾' },
      { name: 'Domates', amount: 0.5, unit: 'küçük', emoji: '🍅' },
      { name: 'Havuç', amount: 0.5, unit: 'küçük', emoji: '🥕' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
      { name: 'Su', amount: 150, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Bulguru yıkayıp 10 dk suda bekletin.',
      'Havucu rendeleyin, domatesi küçük doğrayın.',
      'Zeytinyağında sebzeleri 2 dk soteleyin.',
      'Bulgur ve suyu ekleyip kısık ateşte 15 dk pişirin.',
      'Kıvamını kontrol edip çatalla ezin.',
    ],
    nutrients: [
      { name: 'Demir', value: 2, unit: 'mg' },
      { name: 'Lif', value: 5, unit: 'g' },
      { name: 'Protein', value: 3, unit: 'g' },
      { name: 'Magnezyum', value: 25, unit: 'mg' },
    ],
    tip: 'Bulgur pilavını pütürlü bırakarak bebeğin doku geçişine yardımcı olabilirsiniz.',
    createdAt: hoursAgo(60),
  },
  {
    id: '19',
    title: 'Balkabaklı Risotto',
    description: 'Kremalı, tatlı ve A vitamini deposu İtalyan esintili tarif.',
    emoji: '🎃',
    ageGroup: '8m',
    prepTime: 30,
    calories: 100,
    servings: 2,
    difficulty: 'medium',
    rating: { average: 4.6, count: 27 },
    likes: 115,
    views: 650,
    comments: 10,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: [],
    tags: ['A Vitamini', 'Kremalı', 'Orta'],
    ingredients: [
      { name: 'Pirinç', amount: 3, unit: 'yemek kaşığı', emoji: '🍚' },
      { name: 'Balkabağı', amount: 100, unit: 'g', emoji: '🎃' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
      { name: 'Su', amount: 300, unit: 'ml', emoji: '💧' },
    ],
    steps: [
      'Balkabağını soyup küçük küpler halinde kesin.',
      'Pirinci yıkayın.',
      'Zeytinyağında balkabağını 2 dk soteleyin.',
      'Pirinç ve su ekleyip kısık ateşte sürekli karıştırarak 20 dk pişirin.',
      'Çatalla ezin veya hafifçe blenderdan geçirin.',
    ],
    nutrients: [
      { name: 'A Vitamini', value: 400, unit: 'mcg' },
      { name: 'Karbonhidrat', value: 22, unit: 'g' },
      { name: 'Lif', value: 2, unit: 'g' },
      { name: 'C Vitamini', value: 8, unit: 'mg' },
    ],
    tip: 'Balkabağı mevsiminde fazla alıp küpler halinde dondurabilirsiniz. Böylece her zaman elinizin altında olur.',
    createdAt: hoursAgo(108),
  },
  {
    id: '20',
    title: 'Peynirli Makarna',
    description: 'Kalsiyum ve protein zengini, çocukların favorisi.',
    emoji: '🧀',
    ageGroup: '8m',
    prepTime: 20,
    calories: 140,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.8, count: 48 },
    likes: 210,
    views: 1450,
    comments: 35,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: ['wheat', 'milk'],
    tags: ['Kalsiyum', 'Protein', 'Favorit'],
    ingredients: [
      { name: 'Bebek makarnası', amount: 30, unit: 'g', emoji: '🍝' },
      { name: 'Lor peyniri', amount: 1, unit: 'yemek kaşığı', emoji: '🧀' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
      { name: 'Domates', amount: 0.5, unit: 'küçük', emoji: '🍅' },
    ],
    steps: [
      'Makarnayı bol suda yumuşayana kadar haşlayın.',
      'Domatesi kabuğunu soyup rendeleyin.',
      'Makarnayı süzüp domates, lor peyniri ve zeytinyağı ile karıştırın.',
      'Çatalla hafifçe ezin (8 aylık için).',
    ],
    nutrients: [
      { name: 'Kalsiyum', value: 80, unit: 'mg' },
      { name: 'Protein', value: 6, unit: 'g' },
      { name: 'Karbonhidrat', value: 25, unit: 'g' },
      { name: 'B12 Vitamini', value: 0.2, unit: 'mcg' },
    ],
    tip: 'Tuz eklemeyin. Lor peyniri doğal olarak hafif tuzludur, bu yeterlidir.',
    createdAt: hoursAgo(24),
  },
];

// =============================================
// 12+ AY TARİFLERİ (Aile Sofrası & Parmak Yiyecekler)
// =============================================

const RECIPES_12M: RecipeData[] = [
  {
    id: '4',
    title: 'Somon Püresi',
    description: 'Omega-3 zengini, beyin gelişimini destekleyen tarif.',
    emoji: '🐟',
    ageGroup: '12m+',
    prepTime: 30,
    calories: 130,
    servings: 1,
    difficulty: 'hard',
    rating: { average: 4.0, count: 12 },
    likes: 56,
    views: 310,
    comments: 5,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: ['fish'],
    tags: ['Zor', 'Omega-3'],
    ingredients: [
      { name: 'Somon fileto', amount: 50, unit: 'g', emoji: '🐟' },
      { name: 'Patates', amount: 1, unit: 'küçük', emoji: '🥔' },
      { name: 'Havuç', amount: 1, unit: 'küçük', emoji: '🥕' },
      { name: 'Limon suyu', amount: 1, unit: 'damla', emoji: '🍋' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Somonu buharla 10 dakika pişirin.',
      'Patates ve havucu soyup küçük doğrayın, buharda 15 dk pişirin.',
      'Somon kılığını dikkatle ayıklayın.',
      'Tüm malzemeleri blenderdan geçirin.',
      'Limon suyu ve zeytinyağı ekleyip karıştırın.',
    ],
    nutrients: [
      { name: 'Omega-3', value: 500, unit: 'mg' },
      { name: 'Protein', value: 10, unit: 'g' },
      { name: 'D Vitamini', value: 5, unit: 'mcg' },
      { name: 'Demir', value: 1, unit: 'mg' },
    ],
    tip: 'Somon alırken kemik ve kılık kontrolü çok önemlidir. İyice ayıklayın.',
    createdAt: hoursAgo(72),
  },
  {
    id: '21',
    title: 'Mini Köfteler',
    description: 'Protein ve demir deposu, parmak yiyecek olarak ideal.',
    emoji: '🧆',
    ageGroup: '12m+',
    prepTime: 30,
    calories: 150,
    servings: 6,
    difficulty: 'medium',
    rating: { average: 4.8, count: 55 },
    likes: 234,
    views: 1600,
    comments: 40,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: ['wheat', 'egg'],
    tags: ['Protein', 'Demir ↑', 'Parmak Yiyecek'],
    ingredients: [
      { name: 'Dana kıyma', amount: 100, unit: 'g', emoji: '🥩' },
      { name: 'Yulaf unu', amount: 2, unit: 'yemek kaşığı', emoji: '🌾' },
      { name: 'Yumurta sarısı', amount: 1, unit: 'adet', emoji: '🥚' },
      { name: 'Soğan (rendelenmiş)', amount: 1, unit: 'yemek kaşığı', emoji: '🧅' },
      { name: 'Maydanoz', amount: 1, unit: 'çay kaşığı', emoji: '🌿' },
    ],
    steps: [
      'Tüm malzemeleri bir kasede iyice yoğurun.',
      'Ceviz büyüklüğünde yuvarlak köfteler şekillendirin.',
      'Fırın tepsisine yağlı kağıt serin.',
      'Köfteleri dizin, 180°C fırında 20 dakika pişirin.',
      'Ortasını kontrol edin, pembe kalmamış olmalı.',
    ],
    nutrients: [
      { name: 'Protein', value: 12, unit: 'g' },
      { name: 'Demir', value: 3, unit: 'mg' },
      { name: 'Çinko', value: 2.5, unit: 'mg' },
      { name: 'B12 Vitamini', value: 1, unit: 'mcg' },
    ],
    tip: 'Köfteleri fazla yapıp dondurabilirsiniz. İhtiyaç olunca çözüp ısıtmak çok pratik.',
    createdAt: hoursAgo(18),
  },
  {
    id: '22',
    title: 'Sebzeli Omlet',
    description: 'Kahvaltının yıldızı, protein ve vitamin deposu.',
    emoji: '🍳',
    ageGroup: '12m+',
    prepTime: 10,
    calories: 120,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.6, count: 40 },
    likes: 175,
    views: 1100,
    comments: 22,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: ['egg'],
    tags: ['Protein', 'Kahvaltı', 'Kolay'],
    ingredients: [
      { name: 'Yumurta', amount: 1, unit: 'adet', emoji: '🥚' },
      { name: 'Domates', amount: 0.5, unit: 'küçük', emoji: '🍅' },
      { name: 'Biber', amount: 0.25, unit: 'adet', emoji: '🫑' },
      { name: 'Tereyağı', amount: 0.5, unit: 'çay kaşığı', emoji: '🧈' },
    ],
    steps: [
      'Yumurtayı çırpın.',
      'Domates ve biberi çok küçük doğrayın.',
      'Tavada tereyağını eritin.',
      'Yumurtayı dökün, sebzeleri ekleyin.',
      'Kısık ateşte 3-4 dakika pişirip katlayın.',
    ],
    nutrients: [
      { name: 'Protein', value: 7, unit: 'g' },
      { name: 'D Vitamini', value: 1, unit: 'mcg' },
      { name: 'C Vitamini', value: 15, unit: 'mg' },
      { name: 'Kolin', value: 120, unit: 'mg' },
    ],
    tip: 'Omleti parmak şeklinde kesip bebeğin kendi yemesini sağlayın. BLW için harika!',
    createdAt: hoursAgo(8),
  },
  {
    id: '23',
    title: 'Mücver (Kabak Köftesi)',
    description: 'Türk mutfağı klasiği, sebze yedirmenin en kolay yolu.',
    emoji: '🥒',
    ageGroup: '12m+',
    prepTime: 25,
    calories: 100,
    servings: 8,
    difficulty: 'medium',
    rating: { average: 4.7, count: 38 },
    likes: 187,
    views: 1200,
    comments: 28,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: ['egg', 'wheat', 'milk'],
    tags: ['Türk Mutfağı', 'Sebze', 'Parmak Yiyecek'],
    ingredients: [
      { name: 'Kabak', amount: 1, unit: 'orta', emoji: '🥒' },
      { name: 'Yumurta', amount: 1, unit: 'adet', emoji: '🥚' },
      { name: 'Un', amount: 2, unit: 'yemek kaşığı', emoji: '🌾' },
      { name: 'Beyaz peynir', amount: 1, unit: 'yemek kaşığı', emoji: '🧀' },
      { name: 'Dereotu', amount: 1, unit: 'dal', emoji: '🌿' },
    ],
    steps: [
      'Kabağı rendeleyin, tuzlayıp 10 dk bekletin, suyunu sıkın.',
      'Yumurta, un, ufalanmış peynir ve doğranmış dereotu ekleyin.',
      'İyice karıştırın.',
      'Yağlı kağıt serili tepsiye kaşıkla yuvarlaklar oluşturun.',
      '180°C fırında 20 dakika altı üstü kızarana kadar pişirin.',
    ],
    nutrients: [
      { name: 'Kalsiyum', value: 50, unit: 'mg' },
      { name: 'Protein', value: 4, unit: 'g' },
      { name: 'C Vitamini', value: 10, unit: 'mg' },
      { name: 'Lif', value: 1.5, unit: 'g' },
    ],
    tip: 'Kızartma yerine fırında pişirmek hem sağlıklı hem de daha az dağınık.',
    createdAt: hoursAgo(50),
  },
  {
    id: '24',
    title: 'Pancake (Bebek Pankek)',
    description: 'Yumuşacık, parmak yiyecek olarak mükemmel kahvaltılık.',
    emoji: '🥞',
    ageGroup: '12m+',
    prepTime: 15,
    calories: 90,
    servings: 6,
    difficulty: 'easy',
    rating: { average: 4.9, count: 60 },
    likes: 256,
    views: 1800,
    comments: 45,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: ['wheat', 'egg', 'milk'],
    tags: ['Kahvaltı', 'Parmak Yiyecek', 'Favorit'],
    ingredients: [
      { name: 'Muz', amount: 1, unit: 'olgun', emoji: '🍌' },
      { name: 'Yumurta', amount: 1, unit: 'adet', emoji: '🥚' },
      { name: 'Yulaf unu', amount: 3, unit: 'yemek kaşığı', emoji: '🌾' },
      { name: 'Süt', amount: 50, unit: 'ml', emoji: '🥛' },
      { name: 'Tereyağı', amount: 0.5, unit: 'çay kaşığı', emoji: '🧈' },
    ],
    steps: [
      'Muzu çatalla iyice ezin.',
      'Yumurta, yulaf unu ve süt ekleyip karıştırın.',
      'Tavayı kısık ateşte ısıtıp az tereyağı sürün.',
      'Kaşıkla küçük yuvarlaklar dökün.',
      'Her iki tarafı 2 dakika pişirin.',
    ],
    nutrients: [
      { name: 'Karbonhidrat', value: 15, unit: 'g' },
      { name: 'Protein', value: 4, unit: 'g' },
      { name: 'Potasyum', value: 150, unit: 'mg' },
      { name: 'B6 Vitamini', value: 0.2, unit: 'mg' },
    ],
    tip: 'Şeker eklemeyin, muzun doğal tatlılığı yeterli. Yanına meyve püresi ile servis edebilirsiniz.',
    createdAt: hoursAgo(3),
  },
  {
    id: '25',
    title: 'Fırında Sebze Çubukları',
    description: 'BLW için ideal, renkli ve besleyici parmak sebzeler.',
    emoji: '🥕',
    ageGroup: '12m+',
    prepTime: 30,
    calories: 70,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.4, count: 32 },
    likes: 143,
    views: 880,
    comments: 18,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: [],
    tags: ['BLW', 'Parmak Yiyecek', 'Kolay'],
    ingredients: [
      { name: 'Havuç', amount: 1, unit: 'orta', emoji: '🥕' },
      { name: 'Tatlı Patates', amount: 0.5, unit: 'küçük', emoji: '🍠' },
      { name: 'Kabak', amount: 0.5, unit: 'küçük', emoji: '🥒' },
      { name: 'Zeytinyağı', amount: 1, unit: 'yemek kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Fırını 200 dereceye ısıtın.',
      'Sebzeleri parmak şeklinde uzun çubuklar halinde kesin.',
      'Zeytinyağı ile kaplayın.',
      'Yağlı kağıt serili tepsiye dizin.',
      '25 dakika yumuşayana kadar pişirin.',
    ],
    nutrients: [
      { name: 'A Vitamini', value: 300, unit: 'mcg' },
      { name: 'C Vitamini', value: 12, unit: 'mg' },
      { name: 'Lif', value: 3, unit: 'g' },
      { name: 'Potasyum', value: 200, unit: 'mg' },
    ],
    tip: 'Sebzeler çatalla kolayca ezilebilecek kadar yumuşak olmalı. Test edin.',
    createdAt: hoursAgo(40),
  },
  {
    id: '26',
    title: 'Keçi Peynirli Makarna',
    description: 'Farklı bir lezzet, kalsiyum ve protein deposu.',
    emoji: '🍝',
    ageGroup: '12m+',
    prepTime: 15,
    calories: 160,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.3, count: 20 },
    likes: 88,
    views: 520,
    comments: 9,
    isLiked: false,
    isAIGenerated: false,
    source: 'community',
    authorName: 'Zeynep Hanım',
    authorVerified: false,
    allergens: ['wheat', 'milk'],
    tags: ['Kalsiyum', 'Protein', 'Kolay'],
    ingredients: [
      { name: 'Fiyonk makarna', amount: 40, unit: 'g', emoji: '🍝' },
      { name: 'Keçi peyniri', amount: 1, unit: 'yemek kaşığı', emoji: '🧀' },
      { name: 'Ispanak', amount: 3, unit: 'yaprak', emoji: '🥬' },
      { name: 'Zeytinyağı', amount: 1, unit: 'çay kaşığı', emoji: '🫒' },
    ],
    steps: [
      'Makarnayı haşlayın.',
      'Ispanağı yıkayıp ince kıyın.',
      'Makarnayı süzüp ıspanak, peynir ve zeytinyağı ile karıştırın.',
      'Keçi peyniri eriyene kadar karıştırın.',
    ],
    nutrients: [
      { name: 'Kalsiyum', value: 100, unit: 'mg' },
      { name: 'Protein', value: 8, unit: 'g' },
      { name: 'Demir', value: 1.5, unit: 'mg' },
      { name: 'Karbonhidrat', value: 28, unit: 'g' },
    ],
    tip: 'Keçi peyniri inek sütü alerjisi olan bebekler için alternatif olabilir, ancak doktorunuza danışın.',
    createdAt: hoursAgo(130),
  },
  {
    id: '27',
    title: 'Pirinç Pilavı (Bebek Versiyonu)',
    description: 'Tuzsuz, tereyağlı, sade ve doyurucu pilav.',
    emoji: '🍚',
    ageGroup: '12m+',
    prepTime: 25,
    calories: 130,
    servings: 2,
    difficulty: 'easy',
    rating: { average: 4.5, count: 35 },
    likes: 155,
    views: 920,
    comments: 16,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: ['milk'],
    tags: ['Türk Mutfağı', 'Doyurucu', 'Kolay'],
    ingredients: [
      { name: 'Pirinç', amount: 3, unit: 'yemek kaşığı', emoji: '🍚' },
      { name: 'Tereyağı', amount: 1, unit: 'çay kaşığı', emoji: '🧈' },
      { name: 'Tavuk suyu', amount: 200, unit: 'ml', emoji: '🍗' },
    ],
    steps: [
      'Pirinci yıkayıp 20 dakika suda bekletin.',
      'Tereyağını eritip pirinci 2 dakika kavurun.',
      'Tavuk suyu ekleyip kapağı kapatın.',
      'Kısık ateşte 15 dakika pişirin.',
      '5 dakika dinlendirip çatalla kabartın.',
    ],
    nutrients: [
      { name: 'Karbonhidrat', value: 28, unit: 'g' },
      { name: 'Protein', value: 3, unit: 'g' },
      { name: 'B1 Vitamini', value: 0.1, unit: 'mg' },
      { name: 'Demir', value: 0.5, unit: 'mg' },
    ],
    tip: 'Tavuk suyu yerine sebze suyu da kullanabilirsiniz. Tuzsuz hazırlayın.',
    createdAt: hoursAgo(90),
  },
  {
    id: '28',
    title: 'Mevsim Meyve Salatası',
    description: 'Renkli, vitaminli ve eğlenceli meyve tabağı.',
    emoji: '🍓',
    ageGroup: '12m+',
    prepTime: 10,
    calories: 80,
    servings: 1,
    difficulty: 'easy',
    rating: { average: 4.7, count: 45 },
    likes: 190,
    views: 1250,
    comments: 20,
    isLiked: false,
    isAIGenerated: false,
    source: 'official',
    authorName: 'Kaşık Ekibi',
    authorVerified: true,
    allergens: [],
    tags: ['Vitamin', 'Pişirme Yok', 'Kolay'],
    ingredients: [
      { name: 'Çilek', amount: 3, unit: 'adet', emoji: '🍓' },
      { name: 'Muz', amount: 0.5, unit: 'adet', emoji: '🍌' },
      { name: 'Kivi', amount: 0.5, unit: 'adet', emoji: '🥝' },
      { name: 'Yoğurt', amount: 2, unit: 'yemek kaşığı', emoji: '🥛' },
    ],
    steps: [
      'Meyveleri yıkayıp küçük parçalara kesin.',
      'Bebeğin yaşına uygun boyutta doğrayın.',
      'Bir kaseye koyun.',
      'Üzerine yoğurt ekleyin.',
    ],
    nutrients: [
      { name: 'C Vitamini', value: 40, unit: 'mg' },
      { name: 'Lif', value: 3, unit: 'g' },
      { name: 'Potasyum', value: 200, unit: 'mg' },
      { name: 'Kalsiyum', value: 40, unit: 'mg' },
    ],
    tip: 'Çilek alerjik reaksiyona neden olabilir. İlk seferde az miktarla deneyin.',
    createdAt: hoursAgo(16),
  },
  {
    id: '29',
    title: 'Mantı (Mini Bebek Mantısı)',
    description: 'Türk mutfağının en sevilen yemeğinin bebek versiyonu.',
    emoji: '🥟',
    ageGroup: '12m+',
    prepTime: 60,
    calories: 170,
    servings: 4,
    difficulty: 'hard',
    rating: { average: 4.9, count: 30 },
    likes: 220,
    views: 1400,
    comments: 38,
    isLiked: false,
    isAIGenerated: false,
    source: 'community',
    authorName: 'Fatma Teyze',
    authorVerified: false,
    allergens: ['wheat', 'egg', 'milk'],
    tags: ['Türk Mutfağı', 'Protein', 'Zor'],
    ingredients: [
      { name: 'Un', amount: 1, unit: 'su bardağı', emoji: '🌾' },
      { name: 'Yumurta', amount: 1, unit: 'adet', emoji: '🥚' },
      { name: 'Dana kıyma', amount: 100, unit: 'g', emoji: '🥩' },
      { name: 'Soğan', amount: 0.5, unit: 'küçük', emoji: '🧅' },
      { name: 'Yoğurt', amount: 3, unit: 'yemek kaşığı', emoji: '🥛' },
    ],
    steps: [
      'Un, yumurta ve az su ile hamur yoğurun, 30 dk dinlendirin.',
      'Kıyma ve rendelenmiş soğanı karıştırın.',
      'Hamuru ince açıp küçük kareler kesin.',
      'İç harcı koyup kapatın.',
      'Kaynar suda 10-15 dakika haşlayın.',
      'Yoğurt ile servis edin.',
    ],
    nutrients: [
      { name: 'Protein', value: 14, unit: 'g' },
      { name: 'Demir', value: 2.5, unit: 'mg' },
      { name: 'Kalsiyum', value: 60, unit: 'mg' },
      { name: 'Karbonhidrat', value: 22, unit: 'g' },
    ],
    tip: 'Mantıyı fazla yapıp dondurabilirsiniz. Taze gibi pişer ve çok pratiktir.',
    createdAt: hoursAgo(55),
  },
];

// ===== TÜM TARİFLER =====

export const ALL_RECIPES: RecipeData[] = [
  ...RECIPES_6M,
  ...EXTRA_RECIPES_6M,
  ...RECIPES_8M,
  ...EXTRA_RECIPES_8M,
  ...RECIPES_12M,
  ...EXTRA_RECIPES_12M,
];

// ID ile tarif bul
export const RECIPES_BY_ID: Record<string, RecipeData> = Object.fromEntries(
  ALL_RECIPES.map((r) => [r.id, r])
);

// Yaş grubuna göre filtrele
export function getRecipesByAge(ageGroup: '6m' | '8m' | '12m+' | 'all'): RecipeData[] {
  if (ageGroup === 'all') return ALL_RECIPES;
  return ALL_RECIPES.filter((r) => r.ageGroup === ageGroup);
}

// Alerjen kontrolü — verilen alerjenleri İÇERMEYEN tarifleri getir
export function getSafeRecipes(allergens: AllergenType[]): RecipeData[] {
  if (allergens.length === 0) return ALL_RECIPES;
  return ALL_RECIPES.filter(
    (r) => !r.allergens.some((a) => allergens.includes(a))
  );
}

// Topluluk tarifi ekleme — runtime'da RECIPES_BY_ID'ye ekler
let communityRecipeCounter = 1000;
export function addCommunityRecipe(recipe: Omit<RecipeData, 'id' | 'source' | 'isAIGenerated' | 'isLiked' | 'likes' | 'views' | 'comments' | 'rating' | 'createdAt' | 'photoURL'>): RecipeData {
  const id = `community-${++communityRecipeCounter}`;
  const fullRecipe: RecipeData = {
    ...recipe,
    id,
    source: 'community',
    isAIGenerated: false,
    isLiked: false,
    likes: 0,
    views: 0,
    comments: 0,
    rating: { average: 0, count: 0 },
    createdAt: new Date(),
    photoURL: null,
  };
  RECIPES_BY_ID[id] = fullRecipe;
  ALL_RECIPES.push(fullRecipe);
  return fullRecipe;
}

// İstatistikler
export const RECIPE_STATS = {
  total: ALL_RECIPES.length,
  byAge: {
    '6m': RECIPES_6M.length,
    '8m': RECIPES_8M.length,
    '12m+': RECIPES_12M.length,
  },
  official: ALL_RECIPES.filter((r) => r.source === 'official').length,
  community: ALL_RECIPES.filter((r) => r.source === 'community').length,
};
